import { BaseEntity, Column, DB, DefaultQueryBuilder, Entity, SqliteDataSource } from '../src'
import { SqliteQueryBuilder } from '../src/database/sources/sqlite/SqliteQueryBuilder'
import { PostgresQueryBuilder } from '../src/database/sources/postgres/PostgresQueryBuilder'

// ─── Entities ─────────────────────────────────────────────────────────────────

/**
 * Simulates a table with both a JSON column (object) and an array column
 * serialized as JSON — the typical approach for SQLite/MySQL where there are
 * no native array types.
 */
@Entity({ table: 'events' })
class Event extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  /** Array stored as a JSON string: cast: 'array' → stringify on write, parse on read. */
  @Column({ cast: 'array' })
  tagIds!: number[]

  /** Object/array stored as a JSON string: cast: 'json' */
  @Column({ cast: 'json' })
  metadata!: Record<string, any>
}

/**
 * Entity with a single-element array (the original bug: array of length 1
 * was expanded to `($1)` which Postgres/SQLite rejected as a scalar).
 */
@Entity({ table: 'matches' })
class Match extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'array' })
  homeIds!: number[]

  @Column({ cast: 'array' })
  awayIds!: number[]
}

// ─── Suite ────────────────────────────────────────────────────────────────────

// Single shared in-memory SQLite source for all integration suites.
let _sharedSource: SqliteDataSource

beforeAll(async () => {
  _sharedSource = new SqliteDataSource()

  await _sharedSource.execute(`
    CREATE TABLE matches (
      id      INTEGER PRIMARY KEY AUTOINCREMENT,
      homeIds TEXT NOT NULL DEFAULT '[]',
      awayIds TEXT NOT NULL DEFAULT '[]'
    )
  `)

  await _sharedSource.execute(`
    CREATE TABLE events (
      id       INTEGER PRIMARY KEY AUTOINCREMENT,
      name     TEXT NOT NULL,
      tagIds   TEXT NOT NULL DEFAULT '[]',
      metadata TEXT NOT NULL DEFAULT '{}'
    )
  `)

  DB.register(_sharedSource)
})

afterAll(async () => {
  await _sharedSource.close()
})

describe('Array & JSON column support', () => {
  // ── Query builder unit tests ──────────────────────────────────────────────

  describe('DefaultQueryBuilder — buildColumnValue vs buildValue', () => {
    let builder: DefaultQueryBuilder

    beforeEach(() => {
      builder = new DefaultQueryBuilder()
    })

    it('buildValue expande arrays a lista de placeholders (comportamiento original para WHERE IN)', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildValue([10, 20, 30], stmt)

      expect(stmt.sql).toBe('(?, ?, ?)')
      expect(stmt.bindings).toEqual([10, 20, 30])
    })

    it('buildColumnValue trata el array como un único binding (sin expansión)', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([10, 20, 30], stmt)

      expect(stmt.sql).toBe('?')
      expect(stmt.bindings).toHaveLength(1)
      expect(stmt.bindings[0]).toEqual([10, 20, 30])
    })

    it('buildColumnValue con array de un elemento produce un único placeholder', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([42], stmt)

      expect(stmt.sql).toBe('?')
      expect(stmt.bindings).toHaveLength(1)
      expect(stmt.bindings[0]).toEqual([42])
    })

    it('buildColumnValue con array vacío produce un único placeholder', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([], stmt)

      expect(stmt.sql).toBe('?')
      expect(stmt.bindings).toHaveLength(1)
      expect(stmt.bindings[0]).toEqual([])
    })

    it('buildColumnValue con null produce un único placeholder (null)', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue(null, stmt)

      expect(stmt.sql).toBe('?')
      expect(stmt.bindings).toEqual([null])
    })

    it('buildColumnValue con escalar produce un único placeholder', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue(99, stmt)

      expect(stmt.sql).toBe('?')
      expect(stmt.bindings).toEqual([99])
    })

    it('INSERT con campo array genera un único placeholder por columna (no expansión)', () => {
      const { DB: _DB } = require('../src')
      const insertQuery = _DB.insertQuery('matches').setFields({
        homeIds: [1, 2, 3],
        awayIds: [4]
      })

      const stmt = builder.buildQuery(insertQuery)

      // Debe haber exactamente 2 placeholders (uno por columna), no 4
      const placeholderCount = (stmt.sql.match(/\?/g) || []).length

      expect(placeholderCount).toBe(2)
      expect(stmt.bindings).toHaveLength(2)
      expect(stmt.bindings[0]).toEqual([1, 2, 3])
      expect(stmt.bindings[1]).toEqual([4])
    })

    it('UPDATE con campo array genera un único placeholder por columna (no expansión)', () => {
      const { DB: _DB } = require('../src')
      const updateQuery = _DB.updateQuery('matches').setFields({ homeIds: [5, 6] })

      const stmt = builder.buildQuery(updateQuery)

      const placeholderCount = (stmt.sql.match(/\?/g) || []).length

      expect(placeholderCount).toBe(1)
      expect(stmt.bindings[0]).toEqual([5, 6])
    })

    it('whereIn sigue expandiendo arrays correctamente (regresión)', () => {
      const { DB: _DB } = require('../src')
      const selectQuery = _DB.selectQuery('matches').whereIn('id', [1, 2, 3])
      const stmt = builder.buildQuery(selectQuery)

      // IN debe expandirse: IN (?, ?, ?)
      expect(stmt.sql).toContain('(?, ?, ?)')
      expect(stmt.bindings).toEqual([1, 2, 3])
    })

    it('BETWEEN sigue usando placeholders individuales (regresión)', () => {
      const { DB: _DB } = require('../src')
      const selectQuery = _DB.selectQuery('matches').whereBetween('id', [1, 10])
      const stmt = builder.buildQuery(selectQuery)

      expect(stmt.sql).toContain('BETWEEN ? AND ?')
      expect(stmt.bindings).toEqual([1, 10])
    })
  })

  // ── Serialización dialect-aware en los query builders ────────────────────

  describe('SqliteQueryBuilder — buildColumnValue serializa arrays a JSON', () => {
    let builder: SqliteQueryBuilder

    beforeEach(() => {
      builder = new SqliteQueryBuilder()
    })

    it('un array de números se convierte en JSON string como binding único', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([1, 2, 3], stmt)

      expect(stmt.sql).toBe('?')
      expect(stmt.bindings).toHaveLength(1)
      expect(stmt.bindings[0]).toBe('[1,2,3]')
    })

    it('un array vacío se convierte en "[]"', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([], stmt)

      expect(stmt.bindings[0]).toBe('[]')
    })

    it('un array de un elemento se convierte en "[42]"', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([42], stmt)

      expect(stmt.bindings[0]).toBe('[42]')
    })

    it('un escalar pasa sin cambios', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue(99, stmt)

      expect(stmt.bindings[0]).toBe(99)
    })

    it('whereIn sigue expandiendo arrays (no usa buildColumnValue)', () => {
      const { DB: _DB } = require('../src')
      const query = _DB.selectQuery('matches').whereIn('id', [1, 2, 3])
      const stmt = builder.buildQuery(query)

      expect(stmt.sql).toContain('(?, ?, ?)')
      expect(stmt.bindings).toEqual([1, 2, 3])
    })
  })

  describe('PostgresQueryBuilder — buildColumnValue pasa arrays como binding nativo', () => {
    let builder: PostgresQueryBuilder

    beforeEach(() => {
      builder = new PostgresQueryBuilder()
    })

    it('un array de números se pasa como binding único sin transformar', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([1, 2, 3], stmt)

      expect(stmt.sql).toBe('$1')
      expect(stmt.bindings).toHaveLength(1)
      expect(stmt.bindings[0]).toEqual([1, 2, 3]) // array JS, node-pg lo serializa a {1,2,3}
    })

    it('un array de un elemento se pasa sin transformar', () => {
      const stmt = { sql: '', bindings: [] as any[] }

      ;(builder as any).buildColumnValue([42], stmt)

      expect(stmt.bindings[0]).toEqual([42])
    })

    it('whereIn sigue expandiendo arrays con placeholders Postgres ($1, $2, …)', () => {
      const { DB: _DB } = require('../src')
      const query = _DB.selectQuery('matches').whereIn('id', [1, 2, 3])
      const stmt = builder.buildQuery(query)

      expect(stmt.sql).toContain('($1, $2, $3)')
      expect(stmt.bindings).toEqual([1, 2, 3])
    })
  })

  // ── cast: 'array' — integración con SQLite ────────────────────────────────

  describe("cast: 'array' — integración SQLite", () => {
    beforeEach(async () => {
      await _sharedSource.execute('DELETE FROM matches')
    })

    it('INSERT — persiste un array y lo lee de vuelta como array JS', async () => {
      const match = new Match() as any

      match.homeIds = [1, 2, 3]
      match.awayIds = [4, 5]
      await match.save()

      const found = await Match.find(match.id)

      expect(found.homeIds).toEqual([1, 2, 3])
      expect(found.awayIds).toEqual([4, 5])
    })

    it('INSERT — array de un único elemento (bug original: longitud 1)', async () => {
      const match = new Match() as any

      match.homeIds = [7]
      match.awayIds = [99]
      await match.save()

      const found = await Match.find(match.id)

      expect(found.homeIds).toEqual([7])
      expect(found.awayIds).toEqual([99])
    })

    it('INSERT — array vacío', async () => {
      const match = new Match() as any

      match.homeIds = []
      match.awayIds = []
      await match.save()

      const found = await Match.find(match.id)

      expect(found.homeIds).toEqual([])
      expect(found.awayIds).toEqual([])
    })

    it('UPDATE — reemplaza un array por otro', async () => {
      const match = new Match() as any

      match.homeIds = [1]
      match.awayIds = [2]
      await match.save()

      match.homeIds = [10, 20, 30]
      await match.save()

      const found = await Match.find(match.id)

      expect(found.homeIds).toEqual([10, 20, 30])
      expect(found.awayIds).toEqual([2]) // sin cambios
    })

    it('el valor se almacena como JSON string en la DB (verificación interna)', async () => {
      const match = new Match() as any

      match.homeIds = [1, 2]
      match.awayIds = [3]
      await match.save()

      // Leer el raw de la DB sin pasar por el ORM
      const raw = await _sharedSource.table('matches').where('id', match.id).first()

      expect(raw!.homeIds).toBe('[1,2]')
      expect(raw!.awayIds).toBe('[3]')
    })

    it('múltiples partidos con arrays distintos se hidratan de forma independiente', async () => {
      const m1 = new Match() as any

      m1.homeIds = [1, 2]
      m1.awayIds = [3, 4]
      await m1.save()

      const m2 = new Match() as any

      m2.homeIds = [5]
      m2.awayIds = [6, 7, 8]
      await m2.save()

      const matches = await Match.orderBy('id').get()

      expect(matches[0].homeIds).toEqual([1, 2])
      expect(matches[0].awayIds).toEqual([3, 4])
      expect(matches[1].homeIds).toEqual([5])
      expect(matches[1].awayIds).toEqual([6, 7, 8])
    })
  })

  // ── cast: 'json' — integración con SQLite ─────────────────────────────────

  describe("cast: 'json' — integración SQLite", () => {
    beforeEach(async () => {
      await _sharedSource.execute('DELETE FROM events')
    })

    it('INSERT — persiste un objeto JSON y lo lee de vuelta', async () => {
      const event = new Event() as any

      event.name = 'Conferencia'
      event.tagIds = [10, 20]
      event.metadata = { location: 'Buenos Aires', capacity: 500 }
      await event.save()

      const found = await Event.find(event.id)

      expect(found.metadata).toEqual({ location: 'Buenos Aires', capacity: 500 })
    })

    it('INSERT — persiste tagIds (cast: array) junto con metadata (cast: json)', async () => {
      const event = new Event() as any

      event.name = 'Workshop'
      event.tagIds = [1, 2, 3]
      event.metadata = { online: true }
      await event.save()

      const found = await Event.find(event.id)

      expect(found.tagIds).toEqual([1, 2, 3])
      expect(found.metadata).toEqual({ online: true })
    })

    it('UPDATE — reemplaza el objeto metadata correctamente', async () => {
      const event = new Event() as any

      event.name = 'Meetup'
      event.tagIds = [5]
      event.metadata = { speakers: 3 }
      await event.save()

      event.metadata = { speakers: 5, venue: 'Online' }
      await event.save()

      const found = await Event.find(event.id)

      expect(found.metadata).toEqual({ speakers: 5, venue: 'Online' })
    })

    it('cast: json con un array como valor (JSONB-style)', async () => {
      const event = new Event() as any

      event.name = 'Hackathon'
      event.tagIds = [99]
      event.metadata = [{ id: 1, label: 'backend' }, { id: 2, label: 'frontend' }]
      await event.save()

      const found = await Event.find(event.id)

      expect(Array.isArray(found.metadata)).toBe(true)
      expect(found.metadata).toHaveLength(2)
      expect(found.metadata[0].label).toBe('backend')
    })

    it('el valor metadata se almacena como JSON string en la DB', async () => {
      const event = new Event() as any

      event.name = 'Test'
      event.tagIds = []
      event.metadata = { key: 'value' }
      await event.save()

      const raw = await _sharedSource.table('events').where('id', event.id).first()

      expect(raw!.metadata).toBe('{"key":"value"}')
    })

    it('whereIn sigue funcionando correctamente sobre columnas normales (regresión)', async () => {
      const e1 = new Event() as any

      e1.name = 'E1'
      e1.tagIds = []
      e1.metadata = {}
      await e1.save()

      const e2 = new Event() as any

      e2.name = 'E2'
      e2.tagIds = []
      e2.metadata = {}
      await e2.save()

      const results = await Event.whereIn('name', ['E1', 'E2']).get()

      expect(results).toHaveLength(2)
    })
  })

  // ── casts unitarios — applyCast / applyCastForStorage ─────────────────────

  describe('applyCast y applyCastForStorage para array', () => {
    let applyCast: (value: any, type: any) => any
    let applyCastForStorage: (value: any, type: any) => any

    beforeAll(async () => {
      const casts = await import('../src/entities/decorators/casts')

      applyCast = casts.applyCast
      applyCastForStorage = casts.applyCastForStorage
    })

    describe('applyCastForStorage — array', () => {
      it('devuelve el array tal cual (la serialización la hace el query builder de cada engine)', () => {
        expect(applyCastForStorage([1, 2, 3], 'array')).toEqual([1, 2, 3])
      })

      it('devuelve un array vacío tal cual', () => {
        expect(applyCastForStorage([], 'array')).toEqual([])
      })

      it('devuelve null si el valor es null', () => {
        expect(applyCastForStorage(null, 'array')).toBeNull()
      })
    })

    describe('applyCast — array', () => {
      it('parsea un JSON string a array JS', () => {
        expect(applyCast('[1,2,3]', 'array')).toEqual([1, 2, 3])
      })

      it('pasa un array JS sin tocarlo (ya está parseado, ej: Postgres native)', () => {
        expect(applyCast([4, 5, 6], 'array')).toEqual([4, 5, 6])
      })

      it('parsea un array vacío', () => {
        expect(applyCast('[]', 'array')).toEqual([])
      })

      it('devuelve null si el valor es null', () => {
        expect(applyCast(null, 'array')).toBeNull()
      })
    })
  })
})
