import { BaseEntity, Column, DB, Entity, SelectQuery, SqliteDataSource } from '../src'
import { PostgresQueryBuilder } from '../src/database/sources/postgres/PostgresQueryBuilder'
import { SqliteQueryBuilder } from '../src/database/sources/sqlite/SqliteQueryBuilder'

/**
 * whereArrayContains / orWhereArrayContains — membership of a scalar inside an
 * array column. Compiled to the PostgreSQL `@>` containment operator (GIN
 * friendly) and to a SQLite `json_each()` EXISTS subquery.
 */

@Entity({ table: 'competitors' })
class Competitor extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'array' })
  playerIds!: number[]
}

function buildSql(Builder: new () => any, configure: (q: SelectQuery) => void): { sql: string; bindings: any[] } {
  const query = new SelectQuery('competitors')

  query.setSelectFields(['*'])
  configure(query)

  const statement = { sql: '', bindings: [] as any[] }

  new Builder().buildSelectQuery(query, statement)

  return statement
}

describe('whereArrayContains', () => {
  describe('SQL generation', () => {
    it('PostgreSQL uses the @> containment operator against a cast ARRAY literal', () => {
      const { sql, bindings } = buildSql(PostgresQueryBuilder, (q) => q.whereArrayContains('playerIds', 42))

      // The ARRAY literal is cast to int[] so a text-bound parameter still matches
      // an integer[] column (otherwise: "operator does not exist: integer[] @> text[]").
      expect(sql).toBe('SELECT * FROM competitors WHERE playerIds @> ARRAY[$1]::int[]')
      expect(bindings).toEqual([42])
    })

    it('SQLite expands the JSON array with json_each()', () => {
      const { sql, bindings } = buildSql(SqliteQueryBuilder, (q) => q.whereArrayContains('playerIds', 42))

      expect(sql).toBe('SELECT * FROM competitors WHERE EXISTS (SELECT 1 FROM json_each(playerIds) WHERE value = ?)')
      expect(bindings).toEqual([42])
    })

    it('supports OR-connected membership', () => {
      const { sql, bindings } = buildSql(PostgresQueryBuilder, (q) =>
        q.whereArrayContains('playerIds', 1).orWhereArrayContains('playerIds', 2)
      )

      expect(sql).toBe(
        'SELECT * FROM competitors WHERE playerIds @> ARRAY[$1]::int[] OR playerIds @> ARRAY[$2]::int[]'
      )
      expect(bindings).toEqual([1, 2])
    })

    it('qualifies the array column when a table prefix is given', () => {
      const { sql } = buildSql(PostgresQueryBuilder, (q) => q.whereArrayContains('competitors.playerIds', 7))

      expect(sql).toBe('SELECT * FROM competitors WHERE competitors.playerIds @> ARRAY[$1]::int[]')
    })
  })

  describe('execution against real SQLite', () => {
    let source: SqliteDataSource

    beforeAll(async () => {
      source = new SqliteDataSource()

      await source.execute(`
        CREATE TABLE competitors (
          id        INTEGER PRIMARY KEY AUTOINCREMENT,
          playerIds TEXT NOT NULL DEFAULT '[]'
        )
      `)

      DB.register(source)

      await DB.table('competitors').insert({ playerIds: JSON.stringify([10, 20]) })
      await DB.table('competitors').insert({ playerIds: JSON.stringify([30]) })
      await DB.table('competitors').insert({ playerIds: JSON.stringify([]) })
    })

    afterAll(async () => {
      await source.close()
    })

    it('finds the row whose array contains the value (query builder)', async () => {
      const rows = await DB.table('competitors').whereArrayContains('playerIds', 20).get()

      expect(rows.map((r) => r.id)).toEqual([1])
    })

    it('returns nothing when no array contains the value', async () => {
      const rows = await DB.table('competitors').whereArrayContains('playerIds', 999).get()

      expect(rows).toHaveLength(0)
    })

    it('works through the entity layer with an array cast', async () => {
      const matches = await Competitor.whereArrayContains('playerIds', 30).get()

      expect(matches).toHaveLength(1)
      expect(matches[0].playerIds).toEqual([30])
    })

    it('matches with orWhereArrayContains', async () => {
      const rows = await DB.table('competitors')
        .whereArrayContains('playerIds', 10)
        .orWhereArrayContains('playerIds', 30)
        .get()

      expect(rows.map((r) => r.id).sort()).toEqual([1, 2])
    })
  })
})
