import { BaseEntity, Column, DB, Entity, SqliteDataSource, SqliteQueryBuilder } from '../src'

// ─── Model ───────────────────────────────────────────────────────────────────

@Entity({ table: 'players' })
class Player extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'number' })
  points!: number

  @Column({ cast: 'array' })
  tags!: number[] | null

  @Column({ cast: 'date' })
  createdAt!: Date
}

describe('Batch insert', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE players (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        name      TEXT    NOT NULL,
        points    INTEGER NOT NULL DEFAULT 0,
        tags      TEXT,
        createdAt TIMESTAMP
      )
    `)

    await source.execute(`
      CREATE TABLE counters (
        name  TEXT NOT NULL,
        value INTEGER
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM players')
    await source.execute('DELETE FROM counters')
  })

  // ─── DataTable.insert ─────────────────────────────────────────────────────

  test('DataTable.insert still inserts a single row', async () => {
    const affected = await DB.table('counters').insert({ name: 'visits', value: 3 })

    expect(affected).toBe(1)

    const rows = await DB.table('counters').get()

    expect(rows).toHaveLength(1)
    expect(rows[0]).toMatchObject({ name: 'visits', value: 3 })
  })

  test('DataTable.insert writes a batch in a single statement', async () => {
    const affected = await DB.table('counters').insert([
      { name: 'a', value: 1 },
      { name: 'b', value: 2 },
      { name: 'c', value: 3 }
    ])

    expect(affected).toBe(3)

    const rows = await DB.table('counters').orderBy('name').get()

    expect(rows.map((r) => r.name)).toEqual(['a', 'b', 'c'])
    expect(rows.map((r) => Number(r.value))).toEqual([1, 2, 3])
  })

  test('a batch InsertQuery builds one multi-row VALUES statement', () => {
    const statement = new SqliteQueryBuilder().buildQuery(
      DB.insertQuery('counters').setRows([
        { name: 'a', value: 1 },
        { name: 'b', value: 2 }
      ])
    )

    expect(statement.sql).toBe('INSERT INTO counters (name, value) VALUES (?, ?), (?, ?)')
    expect(statement.bindings).toEqual(['a', 1, 'b', 2])
  })

  test('a single-row InsertQuery builds the same SQL as before', () => {
    const statement = new SqliteQueryBuilder().buildQuery(DB.insertQuery('counters').setFields({ name: 'a', value: 1 }))

    expect(statement.sql).toBe('INSERT INTO counters (name, value) VALUES (?, ?)')
    expect(statement.bindings).toEqual(['a', 1])
  })

  test('DataTable.insert unions columns across rows, filling gaps with NULL', async () => {
    await DB.table('counters').insert([{ name: 'a', value: 5 }, { name: 'b' }])

    const rows = await DB.table('counters').orderBy('name').get()

    expect(rows[0]).toMatchObject({ name: 'a', value: 5 })
    expect(rows[1].name).toBe('b')
    expect(rows[1].value).toBeNull()
  })

  test('DataTable.insert with an empty array is a no-op', async () => {
    const affected = await DB.table('counters').insert([])

    expect(affected).toBe(0)
    expect(await DB.table('counters').get()).toHaveLength(0)
  })

  // ─── Entity.insert ────────────────────────────────────────────────────────

  test('Entity.insert maps properties to columns and applies casts', async () => {
    const now = new Date('2026-01-01T10:00:00.000Z')
    const affected = await Player.insert([
      { name: 'Ada', points: 10, tags: [1, 2], createdAt: now },
      { name: 'Bob', points: 20, tags: null, createdAt: now }
    ])

    expect(affected).toBe(2)

    const players = await Player.orderBy('name').get()

    expect(players).toHaveLength(2)
    expect(players[0].name).toBe('Ada')
    expect(players[0].points).toBe(10)
    expect(players[0].tags).toEqual([1, 2])
    expect(players[0].createdAt).toBeInstanceOf(Date)
    expect(players[1].name).toBe('Bob')
    expect(players[1].tags).toBeNull()
  })

  test('Entity.insert ignores auto-generated columns', async () => {
    await Player.insert([{ id: 999, name: 'Cid', points: 1 } as any])

    const cid = await Player.where('name', 'Cid').first()

    expect(cid).not.toBeNull()
    // The id is auto-generated by the engine, not the provided 999.
    expect(cid!.id).not.toBe(999)
  })

  test('Entity.insert with an empty array is a no-op', async () => {
    const affected = await Player.insert([])

    expect(affected).toBe(0)
    expect(await Player.get()).toHaveLength(0)
  })
})
