import {
  BaseEntity,
  BelongsTo,
  BelongsToThrough,
  Column,
  DB,
  Entity,
  HasMany,
  HasOne,
  Repository,
  SqliteDataSource
} from '../src'

// ─── Models ───────────────────────────────────────────────────────────────────

@Entity({ table: 'btt_countries' })
class BttCountry extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string
}

@Entity({ table: 'btt_users' })
class BttUser extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  countryId!: number

  @BelongsTo(() => BttCountry, 'countryId')
  country?: BttCountry

  @HasMany(() => BttProfile, 'userId')
  profiles?: BttProfile[]
}

@Entity({ table: 'btt_profiles' })
class BttProfile extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  userId!: number

  @Column()
  bio!: string

  @BelongsTo(() => BttUser, 'userId')
  user?: BttUser

  /**
   * BttProfile → BelongsToThrough → BttCountry through BttUser
   *   BttProfile.userId   → BttUser.id        (foreignKey='userId',      localKey='id')
   *   BttUser.countryId   → BttCountry.id     (throughForeignKey='countryId', throughLocalKey='id')
   */
  @BelongsToThrough(() => BttCountry, () => BttUser, 'userId', 'countryId')
  country?: BttCountry

  @HasOne(() => BttAddress, 'profileId')
  address?: BttAddress | null
}

@Entity({ table: 'btt_addresses' })
class BttAddress extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  profileId!: number

  @Column()
  street!: string

  @BelongsTo(() => BttProfile, 'profileId')
  profile?: BttProfile

  /**
   * BttAddress → BelongsToThrough → BttUser through BttProfile
   *   BttAddress.profileId → BttProfile.id    (foreignKey='profileId',  localKey='id')
   *   BttProfile.userId    → BttUser.id        (throughForeignKey='userId', throughLocalKey='id')
   */
  @BelongsToThrough(() => BttUser, () => BttProfile, 'profileId', 'userId')
  user?: BttUser
}

// ─── Suite ────────────────────────────────────────────────────────────────────

describe('BelongsToThrough', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE btt_countries (
        id   INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL
      )
    `)
    await source.execute(`
      CREATE TABLE btt_users (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        name      TEXT    NOT NULL,
        countryId INTEGER NOT NULL
      )
    `)
    await source.execute(`
      CREATE TABLE btt_profiles (
        id     INTEGER PRIMARY KEY AUTOINCREMENT,
        userId INTEGER NOT NULL,
        bio    TEXT    NOT NULL DEFAULT ''
      )
    `)
    await source.execute(`
      CREATE TABLE btt_addresses (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        profileId INTEGER NOT NULL,
        street    TEXT    NOT NULL
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  let arId: number, brId: number
  let aliceId: number, bobId: number, charlieId: number
  let aliceProfileId: number, bobProfileId: number

  beforeEach(async () => {
    await source.execute('DELETE FROM btt_addresses')
    await source.execute('DELETE FROM btt_profiles')
    await source.execute('DELETE FROM btt_users')
    await source.execute('DELETE FROM btt_countries')

    // Countries
    await source.execute(`INSERT INTO btt_countries (name) VALUES ('Argentina')`)
    const ar = await source.table('btt_countries').where('name', 'Argentina').first()
    arId = ar!.id

    await source.execute(`INSERT INTO btt_countries (name) VALUES ('Brazil')`)
    const br = await source.table('btt_countries').where('name', 'Brazil').first()
    brId = br!.id

    // Users
    await source.execute(`INSERT INTO btt_users (name, countryId) VALUES ('Alice', ?)`, [arId])
    const alice = await source.table('btt_users').where('name', 'Alice').first()
    aliceId = alice!.id

    await source.execute(`INSERT INTO btt_users (name, countryId) VALUES ('Bob', ?)`, [arId])
    const bob = await source.table('btt_users').where('name', 'Bob').first()
    bobId = bob!.id

    await source.execute(`INSERT INTO btt_users (name, countryId) VALUES ('Charlie', ?)`, [brId])
    const charlie = await source.table('btt_users').where('name', 'Charlie').first()
    charlieId = charlie!.id

    // Profiles
    await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Alice bio')`, [aliceId])
    const aliceProfile = await source.table('btt_profiles').where('userId', aliceId).first()
    aliceProfileId = aliceProfile!.id

    await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Bob bio')`, [bobId])
    const bobProfile = await source.table('btt_profiles').where('userId', bobId).first()
    bobProfileId = bobProfile!.id

    // Addresses
    await source.execute(`INSERT INTO btt_addresses (profileId, street) VALUES (?, '123 Main St')`, [aliceProfileId])
    await source.execute(`INSERT INTO btt_addresses (profileId, street) VALUES (?, '456 Oak Ave')`, [bobProfileId])
  })

  // ─── Decorator metadata ─────────────────────────────────────────────────────

  describe('Decorator metadata', () => {
    it('registers the belongsToThrough relationship on the entity', () => {
      const rel = Repository.get(BttProfile).relationships['country']

      expect(rel).toBeDefined()
      expect(rel.type).toBe('belongsToThrough')
      expect(rel.foreignKey).toBe('userId')
      expect(rel.throughForeignKey).toBe('countryId')
      expect(rel.localKey).toBe('id')
      expect(rel.throughLocalKey).toBe('id')
    })

    it('defaults localKey and throughLocalKey to "id"', () => {
      const rel = Repository.get(BttAddress).relationships['user']

      expect(rel.localKey).toBe('id')
      expect(rel.throughLocalKey).toBe('id')
    })

    it('registers the through model correctly', () => {
      const rel = Repository.get(BttProfile).relationships['country']

      expect(rel.through).toBeDefined()
      expect(rel.through!()).toBe(BttUser)
      expect(rel.related()).toBe(BttCountry)
    })
  })

  // ─── Eager loading (.with) ─────────────────────────────────────────────────

  describe('Eager loading (.with)', () => {
    it('loads the related entity through the intermediate model', async () => {
      const profiles = await Repository.get(BttProfile).with('country').get()
      const aliceProfile = profiles.find((p) => p.userId === aliceId)!
      const bobProfile = profiles.find((p) => p.userId === bobId)!

      expect(aliceProfile.country).toBeDefined()
      expect(aliceProfile.country!.id).toBe(arId)
      expect(aliceProfile.country!.name).toBe('Argentina')

      expect(bobProfile.country).toBeDefined()
      expect(bobProfile.country!.id).toBe(arId)
    })

    it('resolves different intermediate records to different related entities', async () => {
      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Charlie bio')`, [charlieId])

      const profiles = await Repository.get(BttProfile).with('country').get()
      const charlieProfile = profiles.find((p) => p.userId === charlieId)!

      expect(charlieProfile.country!.id).toBe(brId)
      expect(charlieProfile.country!.name).toBe('Brazil')
    })

    it('sets null when the through model has no matching related entity', async () => {
      await source.execute(`INSERT INTO btt_users (name, countryId) VALUES ('Orphan', 9999)`)
      const orphan = await source.table('btt_users').where('name', 'Orphan').first()

      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'orphan bio')`, [orphan!.id])

      const profiles = await Repository.get(BttProfile).with('country').get()
      const orphanProfile = profiles.find((p) => p.userId === orphan!.id)!

      expect(orphanProfile.country).toBeNull()
    })

    it('supports eager loading two levels deep (BttAddress → BttUser through BttProfile)', async () => {
      const addresses = await Repository.get(BttAddress).with('user').get()
      const aliceAddr = addresses.find((a) => a.profileId === aliceProfileId)!
      const bobAddr = addresses.find((a) => a.profileId === bobProfileId)!

      expect(aliceAddr.user).toBeDefined()
      expect(aliceAddr.user!.id).toBe(aliceId)
      expect(aliceAddr.user!.name).toBe('Alice')

      expect(bobAddr.user!.id).toBe(bobId)
    })

    it('applies a callback constraint on the related query', async () => {
      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Charlie bio')`, [charlieId])

      const profiles = await Repository.get(BttProfile)
        .with({ country: (q) => q.whereIn('name', ['Argentina']) })
        .get()

      const aliceProfile = profiles.find((p) => p.userId === aliceId)!
      const charlieProfile = profiles.find((p) => p.userId === charlieId)!

      expect(aliceProfile.country).toBeDefined()
      expect(aliceProfile.country!.name).toBe('Argentina')
      // Charlie's country (Brazil) is filtered out by the callback
      expect(charlieProfile.country).toBeNull()
    })

    it('handles an empty parent set gracefully', async () => {
      await source.execute('DELETE FROM btt_profiles')
      const profiles = await Repository.get(BttProfile).with('country').get()

      expect(profiles).toHaveLength(0)
    })

    it('loads a single entity via .first()', async () => {
      const profile = await Repository.get(BttProfile).with('country').where('userId', aliceId).first()

      expect(profile).not.toBeNull()
      expect(profile!.country).toBeDefined()
      expect(profile!.country!.name).toBe('Argentina')
    })

    it('works with .find()', async () => {
      const profile = await Repository.get(BttProfile).with('country').find(aliceProfileId)

      expect(profile).not.toBeNull()
      expect(profile!.country!.name).toBe('Argentina')
    })
  })

  // ─── whereHas ─────────────────────────────────────────────────────────────

  describe('whereHas', () => {
    it('filters entities that have the related model (basic existence)', async () => {
      const profiles = await Repository.get(BttProfile).whereHas('country').get()

      expect(profiles.length).toBeGreaterThanOrEqual(2)
    })

    it('filters using a constrained whereHas', async () => {
      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Charlie bio')`, [charlieId])

      const profiles = await Repository.get(BttProfile)
        .whereHas('country', (q) => q.whereIn('btt_countries.name', ['Argentina']))
        .get()

      const ids = profiles.map((p) => p.userId)

      expect(ids).toContain(aliceId)
      expect(ids).toContain(bobId)
      expect(ids).not.toContain(charlieId)
    })

    it('excludes all entities when no related record matches', async () => {
      const profiles = await Repository.get(BttProfile)
        .whereHas('country', (q) => q.whereIn('btt_countries.name', ['Nonexistent']))
        .get()

      expect(profiles).toHaveLength(0)
    })

    it('orWhereHas includes rows matching either condition', async () => {
      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Charlie bio')`, [charlieId])

      const profiles = await Repository.get(BttProfile)
        .whereHas('country', (q) => q.whereIn('btt_countries.name', ['Argentina']))
        .orWhereHas('country', (q) => q.whereIn('btt_countries.name', ['Brazil']))
        .get()

      const ids = profiles.map((p) => p.userId)

      expect(ids).toContain(aliceId)
      expect(ids).toContain(bobId)
      expect(ids).toContain(charlieId)
    })
  })

  // ─── joinRelationship ──────────────────────────────────────────────────────

  describe('joinRelationship', () => {
    it('joins through both intermediate and related tables', async () => {
      const profiles = await Repository.get(BttProfile)
        .joinRelationship('country')
        .select('btt_profiles.*')
        .get()

      expect(profiles.length).toBeGreaterThanOrEqual(2)
    })

    it('allows filtering on the joined related table', async () => {
      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'Charlie bio')`, [charlieId])

      const profiles = await Repository.get(BttProfile)
        .joinRelationship('country')
        .whereIn('btt_countries.name', ['Argentina'])
        .get()

      const ids = profiles.map((p) => p.userId)

      expect(ids).toContain(aliceId)
      expect(ids).toContain(bobId)
      expect(ids).not.toContain(charlieId)
    })

    it('leftJoinRelationship includes entities with no matching related', async () => {
      await source.execute(`INSERT INTO btt_users (name, countryId) VALUES ('Orphan', 9999)`)
      const orphan = await source.table('btt_users').where('name', 'Orphan').first()

      await source.execute(`INSERT INTO btt_profiles (userId, bio) VALUES (?, 'orphan bio')`, [orphan!.id])

      const profiles = await Repository.get(BttProfile)
        .leftJoinRelationship('country')
        .select('btt_profiles.*')
        .get()

      // Orphan profile should still appear with a LEFT JOIN
      const ids = profiles.map((p) => p.userId)

      expect(ids).toContain(orphan!.id)
    })
  })

  // ─── Cached through — reutilización de tabla intermedia ya cargada ──────────
  //
  // BelongsToThrough: cuando el modelo intermedio ya está cargado como propiedad
  // de objeto único (BelongsTo), no debe emitirse una segunda query a su tabla.

  describe('Cached through — reutilización de tabla intermedia ya cargada', () => {
    let queriedSqls: string[]

    beforeEach(async () => {
      // Habilitamos debug en el source para que DataConnection loguee cada SQL
      // construido, y espiamos console.log para capturarlos.
      source.setDebugEnabled(true)
      queriedSqls = []
      jest.spyOn(console, 'log').mockImplementation((msg: string) => {
        if (typeof msg === 'string' && msg.startsWith('SQL:')) {
          queriedSqls.push(msg)
        }
      })
    })

    afterEach(() => {
      source.setDebugEnabled(false)
      jest.restoreAllMocks()
    })

    it('belongsToThrough: no re-consulta la tabla intermedia si ya fue cargada con with()', async () => {
      // BttProfile → user    (BelongsTo,        tabla intermedia = btt_users)
      // BttProfile → country (BelongsToThrough  a través de btt_users)
      // Al cargar ambos, la tabla "btt_users" solo debe consultarse una vez.
      const profiles = await Repository.get(BttProfile).with('user', 'country').get()
      const aliceProfile = profiles.find((p) => p.bio === 'Alice bio')!

      // Resultados correctos
      expect(aliceProfile.user).toBeDefined()
      expect(aliceProfile.user!.name).toBe('Alice')
      expect(aliceProfile.country).toBeDefined()
      expect(aliceProfile.country!.name).toBe('Argentina')

      // La tabla "btt_users" no debe aparecer dos veces en las queries emitidas
      const userQueries = queriedSqls.filter((sql) => /FROM\s+"?btt_users"?/i.test(sql))

      expect(userQueries).toHaveLength(1)
    })
  })
})
