import { BaseEntity, Column, DB, Entity, Repository, SqliteDataSource, UpdateQuery } from '../src'

// ─── Entities ───────────────────────────────────────────────────────────────

@Entity({ table: 'users' })
class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  organizationId!: number

  @Column()
  firstName!: string

  @Column()
  lastName!: string

  @Column()
  nickname!: string | null

  @Column()
  phoneNumber!: string

  @Column()
  passwordHash!: string

  @Column({ cast: 'number' })
  roleId!: number

  @Column({ cast: 'boolean' })
  emailVerified!: boolean

  @Column()
  email!: string
}

@Entity({ table: 'events' })
class Event extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'array' })
  tagIds!: number[]

  @Column({ cast: 'json' })
  metadata!: Record<string, any>

  @Column({ cast: 'date' })
  startsAt!: Date
}

// ─── Suite ──────────────────────────────────────────────────────────────────

describe('Dirty tracking', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE users (
        id             INTEGER PRIMARY KEY AUTOINCREMENT,
        organizationId INTEGER NOT NULL,
        firstName      TEXT NOT NULL,
        lastName       TEXT NOT NULL,
        nickname       TEXT,
        phoneNumber    TEXT NOT NULL,
        passwordHash   TEXT NOT NULL,
        roleId         INTEGER NOT NULL,
        emailVerified  INTEGER NOT NULL DEFAULT 0,
        email          TEXT NOT NULL
      )
    `)
    await source.execute(`
      CREATE TABLE events (
        id       INTEGER PRIMARY KEY AUTOINCREMENT,
        name     TEXT NOT NULL,
        tagIds   TEXT NOT NULL DEFAULT '[]',
        metadata TEXT NOT NULL DEFAULT '{}',
        startsAt TEXT NOT NULL
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM users')
    await source.execute('DELETE FROM events')
  })

  function newPlayer(): any {
    const player = new User() as any

    player.organizationId = 1
    player.firstName = 'John'
    player.lastName = 'Doe'
    player.nickname = null
    player.phoneNumber = '555-0100'
    player.passwordHash = 'hash'
    player.roleId = 2
    player.emailVerified = true
    player.email = `seed_${Date.now()}@x.com`

    return player
  }

  // ─── save() solo escribe columnas dirty ───────────────────────────────────

  describe('save() — UPDATE solo escribe columnas dirty', () => {
    it('después de un insert, cambiar un solo campo emite un UPDATE con una sola columna', async () => {
      const player = newPlayer()

      await player.save()

      const spy = jest.spyOn(source, 'execute')

      player.email = 'anotherValue@x.com'
      await player.save()

      const updates = spy.mock.calls
        .map((call) => call[0])
        .filter((query): query is UpdateQuery => query instanceof UpdateQuery)

      spy.mockRestore()

      expect(updates).toHaveLength(1)
      expect(updates[0].getFields()).toEqual({ email: 'anotherValue@x.com' })
    })

    it('el UPDATE real en la base sólo modifica la columna tocada', async () => {
      const player = newPlayer()

      await player.save()
      const id = player.id
      const originalFirstName = player.firstName

      player.email = 'changed@x.com'
      await player.save()

      const row = await source.table('users').where('id', id).first()

      expect(row!.email).toBe('changed@x.com')
      expect(row!.firstName).toBe(originalFirstName)
    })

    it('save() sin cambios no emite ningún UPDATE', async () => {
      const player = newPlayer()

      await player.save()

      const spy = jest.spyOn(source, 'execute')

      await player.save()

      const updateCalls = spy.mock.calls.filter((call) => call[0] instanceof UpdateQuery)

      spy.mockRestore()
      expect(updateCalls).toHaveLength(0)
    })

    it('después de guardar, todos los campos quedan limpios y un cambio posterior sólo afecta a ese campo', async () => {
      const player = newPlayer()

      await player.save()
      expect(player.isDirty()).toBe(false)

      player.firstName = 'Jane'
      expect(player.isDirty()).toBe(true)
      expect(player.isDirty('firstName')).toBe(true)
      expect(player.isDirty('lastName')).toBe(false)

      await player.save()
      expect(player.isDirty()).toBe(false)

      const row = await source.table('users').where('id', player.id).first()

      expect(row!.firstName).toBe('Jane')
      expect(row!.lastName).toBe('Doe')
    })

    it('múltiples cambios encadenados sólo persisten lo modificado en cada save()', async () => {
      const player = newPlayer()

      await player.save()

      player.email = 'first@x.com'
      await player.save()

      player.firstName = 'Updated'
      await player.save()

      const row = await source.table('users').where('id', player.id).first()

      expect(row!.email).toBe('first@x.com')
      expect(row!.firstName).toBe('Updated')
      expect(row!.lastName).toBe('Doe')
    })
  })

  // ─── isDirty() / getDirty() ────────────────────────────────────────────────

  describe('isDirty() / getDirty()', () => {
    it('una entidad recién construida (no guardada) se considera dirty', () => {
      const player = newPlayer()

      expect(player.isDirty()).toBe(true)
    })

    it('getDirty() en una entidad nueva retorna todos los campos seteados', () => {
      const player = newPlayer()
      const dirty = player.getDirty()

      expect(dirty.firstName).toBe('John')
      expect(dirty.email).toBe(player.email)
    })

    it('una entidad recién cargada de la base está limpia', async () => {
      const player = newPlayer()

      await player.save()

      const found: any = await User.find(player.id)

      expect(found.isDirty()).toBe(false)
      expect(found.getDirty()).toEqual({})
    })

    it('modificar un campo en una entidad cargada la marca dirty sólo en ese campo', async () => {
      const player = newPlayer()

      await player.save()

      const found: any = await User.find(player.id)

      found.lastName = 'Smith'

      expect(found.isDirty()).toBe(true)
      expect(found.isDirty('lastName')).toBe(true)
      expect(found.isDirty('firstName')).toBe(false)
      expect(found.getDirty()).toEqual({ lastName: 'Smith' })
    })

    it('reasignar el mismo valor no marca el campo como dirty', async () => {
      const player = newPlayer()

      await player.save()

      const found: any = await User.find(player.id)
      const sameValue: string = found.firstName

      found.firstName = sameValue

      expect(found.isDirty()).toBe(false)
    })

    it('Repository.get(Entity).isDirty/getDirty funcionan igual que los métodos de instancia', async () => {
      const player = newPlayer()

      await player.save()
      player.email = 'via-repo@x.com'

      const repo = Repository.get(User)

      expect(repo.isDirty(player)).toBe(true)
      expect(repo.getDirty(player)).toEqual({ email: 'via-repo@x.com' })
    })
  })

  // ─── Mutación en lugar de campos array/json/date ──────────────────────────

  describe('Dirty tracking en campos array / json / date', () => {
    function newEvent(): any {
      const event = new Event() as any

      event.name = 'Launch'
      event.tagIds = [1, 2]
      event.metadata = { color: 'red' }
      event.startsAt = new Date('2026-01-01T10:00:00.000Z')

      return event
    }

    it('mutar un array cast en el lugar (push) se detecta como dirty', async () => {
      const event = newEvent()

      await event.save()
      const found: any = await Event.find(event.id)

      found.tagIds.push(3)

      expect(found.isDirty('tagIds')).toBe(true)

      await found.save()

      const reloaded: any = await Event.find(event.id)

      expect(reloaded.tagIds).toEqual([1, 2, 3])
    })

    it('mutar una propiedad de un objeto json cast en el lugar se detecta como dirty', async () => {
      const event = newEvent()

      await event.save()
      const found: any = await Event.find(event.id)

      found.metadata.color = 'blue'

      expect(found.isDirty('metadata')).toBe(true)

      await found.save()

      const reloaded: any = await Event.find(event.id)

      expect(reloaded.metadata).toEqual({ color: 'blue' })
    })

    it('reasignar una Date equivalente (mismo instante) no marca el campo dirty', async () => {
      const event = newEvent()

      await event.save()
      const found: any = await Event.find(event.id)

      found.startsAt = new Date(found.startsAt.getTime())

      expect(found.isDirty('startsAt')).toBe(false)
    })

    it('cambiar la Date a otro instante sí marca el campo dirty y persiste sólo ese cambio', async () => {
      const event = newEvent()

      await event.save()
      const found: any = await Event.find(event.id)
      const originalName = found.name

      found.startsAt = new Date('2026-02-01T10:00:00.000Z')
      await found.save()

      const reloaded: any = await Event.find(event.id)

      expect(reloaded.startsAt.toISOString()).toBe('2026-02-01T10:00:00.000Z')
      expect(reloaded.name).toBe(originalName)
    })
  })
})
