import { BaseEntity, BelongsTo, Column, DB, Dto, Entity, HasMany, SqliteDataSource, VirtualColumn } from '../src'

// ─── Model definitions ────────────────────────────────────────────────────────

@Entity({ table: 'countries' })
class Country extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  code!: string

  @HasMany(() => User, 'countryId')
  users?: User[]
}

@Entity()
class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  email!: string

  @Column()
  countryId!: number

  @BelongsTo(() => Country, 'countryId')
  country?: Country

  @VirtualColumn()
  get label(): string {
    return `${this.name} <${this.email}>`
  }

  someMethod(): number {
    return 42
  }
}

// ─── Compile-time assertions ──────────────────────────────────────────────────

type UserDto = Dto<User>
type CountryDto = Dto<Country>

type Expect<T extends true> = T
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false

// Data properties and getters are kept with their original types
export type _id = Expect<Equal<UserDto['id'], number>>
export type _name = Expect<Equal<UserDto['name'], string>>
export type _label = Expect<Equal<UserDto['label'], string>>
// Nested entities and arrays of entities map recursively to their DTO
export type _country = Expect<Equal<UserDto['country'], Dto<Country> | undefined>>
export type _users = Expect<Equal<CountryDto['users'], Array<Dto<User>> | undefined>>
// Optional modifier of relationships is preserved
export type _usersOptional = Expect<Equal<Pick<CountryDto, 'users'>, { users?: Array<Dto<User>> }>>
// Methods and BaseEntity members are stripped
export type _noMethods = Expect<
  Equal<Extract<keyof UserDto, 'someMethod' | 'save' | 'delete' | 'toJSON' | 'toDto'>, never>
>

// ─── Runtime tests ────────────────────────────────────────────────────────────

describe('Dto', () => {
  const source = new SqliteDataSource()

  beforeAll(async () => {
    DB.register(source)
    await source.execute('CREATE TABLE countries (id INTEGER PRIMARY KEY, name TEXT, code TEXT)')
    await source.execute('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email TEXT, countryId INTEGER)')

    const country = new Country()

    country.name = 'Argentina'
    country.code = 'AR'
    await country.save()

    const user = new User()

    user.name = 'Luis'
    user.email = 'luis@test.com'
    user.countryId = country.id
    await user.save()
  })

  afterAll(async () => {
    await source.close()
  })

  test('toDto returns columns and getters, without methods', async () => {
    const user = await User.find(1)
    const dto = user!.toDto()

    expect(dto).toEqual({ id: 1, name: 'Luis', email: 'luis@test.com', countryId: 1, label: 'Luis <luis@test.com>' })
    expect((dto as any).someMethod).toBeUndefined()
    expect((dto as any).save).toBeUndefined()
  })

  test('toDto omits relationships that were not loaded', async () => {
    const country = await Country.find(1)
    const dto = country!.toDto()

    expect(dto).toEqual({ id: 1, name: 'Argentina', code: 'AR' })
    expect('users' in dto).toBe(false)
  })

  test('toDto converts loaded relationships recursively', async () => {
    const country = await Country.with('users').first()
    const dto = country!.toDto()

    expect(dto.users).toHaveLength(1)
    expect(dto.users![0]).toEqual({
      id: 1,
      name: 'Luis',
      email: 'luis@test.com',
      countryId: 1,
      label: 'Luis <luis@test.com>'
    })
    // nested items are plain objects, not entity instances
    expect(dto.users![0]).not.toBeInstanceOf(BaseEntity)
    expect((dto.users![0] as any).save).toBeUndefined()
  })
})
