import { BaseEntity, Column, DB, Entity, EntityQuery, Scope, SqliteDataSource } from '../src'

/**
 * Aggregates and grouped projections at the ENTITY level.
 *
 * The base query builder has had full aggregate support for a while
 * (see aggregate-functions.test.ts), but an entity query only exposed `count`.
 * Everything else had to be written against `DB.table(...)`, which silently
 * drops out of the entity's global scopes — so a multi-tenant filter or a soft
 * delete stops applying exactly where a total is being computed, and the result
 * is not an error but a wrong number.
 *
 * Three things are covered here:
 *   1. `sum` / `avg` / `min` / `max` terminals that apply the global scopes.
 *   2. `having` / `orHaving`, so a grouped entity query can be filtered.
 *   3. `toBase()`, the escape hatch for a projection that is not a row of the
 *      table — and the reason `select('SUM(x) AS total').get()` cannot be it.
 */

/** Only rows of the "current" tenant exist, as far as the application is concerned. */
let currentTenantId: number | null = 1

class TenantScope implements Scope {
  apply(query: EntityQuery<any>): void {
    if (currentTenantId != null) {
      query.where('tenantId', currentTenantId)
    }
  }
}

/** An asynchronous scope — a scope may read a session, so applying it is awaited. */
class AsyncTenantScope implements Scope {
  async apply(query: EntityQuery<any>): Promise<void> {
    await Promise.resolve()

    if (currentTenantId != null) {
      query.where('tenantId', currentTenantId)
    }
  }
}

@Entity({ table: 'payments' })
class Payment extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tenantId!: number

  @Column()
  region!: string

  @Column({ cast: 'number' })
  amount!: number

  /** Declared under a different column name, so field resolution is exercised too. */
  @Column({ columnName: 'settled_at', cast: 'date' })
  settledAt!: Date

  protected static booted(): void {
    Payment.addGlobalScope(new TenantScope())
  }
}

@Entity({ table: 'payments' })
class AsyncPayment extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  tenantId!: number

  @Column({ cast: 'number' })
  amount!: number

  protected static booted(): void {
    AsyncPayment.addGlobalScope(new AsyncTenantScope())
  }
}

describe('Entity-level aggregates', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE payments (
        id         INTEGER PRIMARY KEY AUTOINCREMENT,
        tenantId   INTEGER NOT NULL,
        region     TEXT    NOT NULL,
        amount     REAL    NOT NULL,
        settled_at TEXT    NOT NULL
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    currentTenantId = 1
    await source.execute('DELETE FROM payments')
    // Tenant 1: north 100 + 300, south 50. Tenant 2: a single, much larger row,
    // so any total that accidentally includes it is unmistakable.
    await source.execute(`
      INSERT INTO payments (tenantId, region, amount, settled_at) VALUES
        (1, 'north', 100, '2026-01-10'),
        (1, 'north', 300, '2026-03-05'),
        (1, 'south',  50, '2026-02-01'),
        (2, 'north', 9000, '2026-04-01')
    `)
  })

  describe('scalar terminals', () => {
    it('sums only the rows the global scope allows', async () => {
      expect(await Payment.sum('amount')).toBe(450)
    })

    it('sums the whole table once the scope is lifted', async () => {
      expect(await Payment.withoutGlobalScopes().sum('amount')).toBe(9450)
    })

    it('combines the scope with the query own conditions', async () => {
      expect(await Payment.where('region', 'north').sum('amount')).toBe(400)
    })

    it('sums to 0 when nothing matches', async () => {
      expect(await Payment.where('region', 'west').sum('amount')).toBe(0)
    })

    it('averages the scoped rows', async () => {
      expect(await Payment.avg('amount')).toBe(150)
    })

    it('averages to null when nothing matches, unlike a sum', async () => {
      expect(await Payment.where('region', 'west').avg('amount')).toBeNull()
    })

    it('takes the min and max of the scoped rows', async () => {
      expect(await Payment.min('amount')).toBe(50)
      expect(await Payment.max('amount')).toBe(300)
    })

    it('returns null for min/max when nothing matches', async () => {
      expect(await Payment.where('region', 'west').min('amount')).toBeNull()
      expect(await Payment.where('region', 'west').max('amount')).toBeNull()
    })

    it('resolves a property to its declared column name', async () => {
      // `settledAt` is stored as `settled_at`; a MIN over it has to reach the
      // column, not the property.
      expect(await Payment.min<string>('settledAt')).toBe('2026-01-10')
      expect(await Payment.max<string>('settledAt')).toBe('2026-03-05')
    })

    it('applies an asynchronous scope before aggregating', async () => {
      expect(await AsyncPayment.sum('amount')).toBe(450)
    })

    it('follows the scope when it changes', async () => {
      currentTenantId = 2

      expect(await Payment.sum('amount')).toBe(9000)

      currentTenantId = null

      expect(await Payment.sum('amount')).toBe(9450)
    })
  })

  describe('having', () => {
    it('filters groups on an aggregate', async () => {
      // north totals 400, south 50 — only north clears the bar.
      const groups = await Payment.groupBy('region').having('SUM(amount)', '>=', 400).count()

      expect(groups).toBe(1)
    })

    it('keeps the global scope out of the groups it filters', async () => {
      // Tenant 2's 9000 would put 'north' over any threshold on its own; with
      // the scope applied, a bar above tenant 1's own total excludes everything.
      expect(await Payment.groupBy('region').having('SUM(amount)', '>', 500).count()).toBe(0)
      expect(await Payment.withoutGlobalScopes().groupBy('region').having('SUM(amount)', '>', 500).count()).toBe(1)
    })

    it('accepts an OR-connected condition', async () => {
      const groups = await Payment.groupBy('region')
        .having('SUM(amount)', '>=', 400)
        .orHaving('SUM(amount)', '<', 100)
        .count()

      expect(groups).toBe(2)
    })
  })

  describe('toBase', () => {
    it('returns grouped aggregate rows with the scope applied', async () => {
      const rows = await (await Payment.where('amount', '>', 0).toBase())
        .select('region', 'SUM(amount) AS total')
        .groupBy('region')
        .orderBy('region')
        .get()

      expect(rows).toHaveLength(2)
      expect(rows[0]).toMatchObject({ region: 'north' })
      expect(Number(rows[0].total)).toBe(400)
      expect(Number(rows[1].total)).toBe(50)
    })

    it('honours withoutGlobalScopes', async () => {
      const rows = await (await Payment.withoutGlobalScopes().toBase()).select('SUM(amount) AS total').get()

      expect(Number(rows[0].total)).toBe(9450)
    })

    it('is what select() + get() cannot be, since hydration drops a projection', async () => {
      // Kept as a test rather than a comment: this is the trap toBase() exists
      // for. `get()` maps each row through the entity's declared columns, so an
      // alias the projection invented has nowhere to land — and neither do the
      // real columns, which the projection did not select.
      const [hydrated] = await Payment.select('SUM(amount) AS total').get()

      expect((hydrated as unknown as Record<string, unknown>).total).toBeUndefined()
      expect(hydrated.amount).toBeUndefined()
    })
  })
})
