import {
  BaseEntity,
  BelongsTo,
  Column,
  DB,
  Entity,
  HasMany,
  HasManyThrough,
  HasOne,
  HasOneThrough,
  OrderByDirection,
  Repository,
  SqliteDataSource
} from '../src'

// ─── Model definitions (extend BaseEntity + decorators) ──────────────────────

@Entity({ table: 'countries' })
class Country extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  code!: string

  @HasMany(() => User, 'countryId')
  users?: User[]

  @HasManyThrough(() => Order, () => User, 'userId', 'countryId')
  orders?: Order[]
}

@Entity()
class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  email!: string

  @Column({ cast: 'number' })
  age!: number

  @Column({ cast: 'boolean' })
  active!: boolean

  @Column()
  countryId!: number

  @BelongsTo(() => Country, 'countryId')
  country?: Country

  @HasOne(() => Profile, 'userId')
  profile?: Profile | null

  @HasMany(() => Order, 'userId')
  orders?: Order[]

  @HasOneThrough(() => ShippingAddress, () => Profile, 'profileId', 'userId')
  shippingAddress?: ShippingAddress

  get label(): string {
    return `${this.name} <${this.email}>`
  }
}

@Entity()
class Profile extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  userId!: number

  @Column()
  bio!: string

  @BelongsTo(() => User, 'userId')
  user?: User
}

@Entity()
class Order extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  userId!: number

  @Column()
  product!: string

  @Column({ cast: 'number' })
  amount!: number

  @BelongsTo(() => User, 'userId')
  user?: User
}

@Entity({ table: 'shipping_addresses' })
class ShippingAddress extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  profileId!: number

  @Column()
  street!: string

  @BelongsTo(() => Profile, 'profileId')
  profile?: Profile
}

@Entity({ table: 'employees' })
class Employee extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true, columnName: 'employee_id' })
  id!: number

  @Column({ columnName: 'first_name' })
  firstName!: string

  @Column({ columnName: 'is_active', cast: 'boolean' })
  isActive!: boolean

  @Column()
  email!: string
}

// ─── Aliases — the static query methods are now typed via BaseEntity ──────────
const UserModel = User
const CountryModel = Country
const OrderModel = Order
const EmployeeModel = Employee

// ─── Suite ───────────────────────────────────────────────────────────────────

describe('Entities (Active Record — BaseEntity)', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE countries (
        id   INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        code TEXT NOT NULL
      )
    `)
    await source.execute(`
      CREATE TABLE users (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        name      TEXT    NOT NULL,
        email     TEXT    NOT NULL,
        age       INTEGER NOT NULL,
        active    INTEGER NOT NULL DEFAULT 1,
        countryId INTEGER
      )
    `)
    await source.execute(`
      CREATE TABLE profiles (
        id     INTEGER PRIMARY KEY AUTOINCREMENT,
        userId INTEGER NOT NULL,
        bio    TEXT    NOT NULL DEFAULT ''
      )
    `)
    await source.execute(`
      CREATE TABLE orders (
        id      INTEGER PRIMARY KEY AUTOINCREMENT,
        userId  INTEGER NOT NULL,
        product TEXT    NOT NULL,
        amount  REAL    NOT NULL
      )
    `)
    await source.execute(`
      CREATE TABLE shipping_addresses (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        profileId INTEGER NOT NULL,
        street    TEXT    NOT NULL
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM shipping_addresses')
    await source.execute('DELETE FROM orders')
    await source.execute('DELETE FROM profiles')
    await source.execute('DELETE FROM users')
    await source.execute('DELETE FROM countries')
  })

  // ─── Helpers ─────────────────────────────────────────────────────────────

  async function seedCountries() {
    await source.execute(`INSERT INTO countries (name, code) VALUES ('Argentina', 'AR')`)
    await source.execute(`INSERT INTO countries (name, code) VALUES ('Brazil', 'BR')`)
  }

  async function seedUsers() {
    const ar = await source.table('countries').where('code', 'AR').first()
    const br = await source.table('countries').where('code', 'BR').first()

    await source.execute(
      `INSERT INTO users (name, email, age, active, countryId) VALUES ('Alice', 'alice@example.com', 30, 1, ?)`,
      [ar!.id]
    )
    await source.execute(
      `INSERT INTO users (name, email, age, active, countryId) VALUES ('Bob', 'bob@example.com', 25, 1, ?)`,
      [ar!.id]
    )
    await source.execute(
      `INSERT INTO users (name, email, age, active, countryId) VALUES ('Charlie', 'charlie@example.com', 35, 0, ?)`,
      [br!.id]
    )
  }

  async function seedRelated() {
    const alice = await source.table('users').where('name', 'Alice').first()
    const bob = await source.table('users').where('name', 'Bob').first()

    await source.execute(`INSERT INTO profiles (userId, bio) VALUES (?, 'Alice bio')`, [alice!.id])
    await source.execute(`INSERT INTO profiles (userId, bio) VALUES (?, 'Bob bio')`, [bob!.id])
    const aliceProfile = await source.table('profiles').where('userId', alice!.id).first()

    await source.execute(`INSERT INTO shipping_addresses (profileId, street) VALUES (?, '123 Main St')`, [
      aliceProfile!.id
    ])
    await source.execute(`INSERT INTO orders (userId, product, amount) VALUES (?, 'Widget',    9.99)`, [alice!.id])
    await source.execute(`INSERT INTO orders (userId, product, amount) VALUES (?, 'Gadget',   24.99)`, [alice!.id])
    await source.execute(`INSERT INTO orders (userId, product, amount) VALUES (?, 'Doohickey', 4.99)`, [bob!.id])
  }

  // ─── Decorator metadata ───────────────────────────────────────────────────

  describe('Decorator metadata', () => {
    it('@Entity setea table name por defecto (lowercase + s)', () => {
      expect(Repository.get(UserModel).table).toBe('users') // User → users
      expect(Repository.get(OrderModel).table).toBe('orders') // Order → orders
    })

    it('@Entity respeta table name explícito', () => {
      expect(Repository.get(CountryModel).table).toBe('countries')
    })

    it('@Column registra los fields', () => {
      expect(Repository.get(UserModel).fields).toContain('name')
      expect(Repository.get(UserModel).fields).toContain('email')
      expect(Repository.get(UserModel).fields).toContain('age')
    })

    it('@Column con cast registra el cast correctamente', () => {
      expect(Repository.get(UserModel).casts['age']).toBe('number')
      expect(Repository.get(UserModel).casts['active']).toBe('boolean')
    })

    it('@Column({ primaryKey: true }) setea el primaryKey', () => {
      expect(Repository.get(UserModel).primaryKey).toBe('id')
    })

    it('@Column({ autoGenerated: true }) registra el campo como auto-generado', () => {
      expect(Repository.get(UserModel).autoGeneratedFields).toContain('id')
    })

    it('@HasMany registra la relación correctamente', () => {
      expect(Repository.get(UserModel).relationships['orders']).toBeDefined()
      expect(Repository.get(UserModel).relationships['orders'].type).toBe('hasMany')
    })

    it('@BelongsTo registra la relación correctamente', () => {
      expect(Repository.get(UserModel).relationships['country']).toBeDefined()
      expect(Repository.get(UserModel).relationships['country'].type).toBe('belongsTo')
    })

    it('@HasOne registra la relación correctamente', () => {
      expect(Repository.get(UserModel).relationships['profile']).toBeDefined()
      expect(Repository.get(UserModel).relationships['profile'].type).toBe('hasOne')
    })
  })

  // ─── Hydration & casts ───────────────────────────────────────────────────

  describe('Hydration & casts', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
    })

    it('retorna instancias de la clase decorada', async () => {
      const users = await UserModel.get()

      expect(users[0]).toBeInstanceOf(User)
    })

    it('aplica cast number al campo age', async () => {
      const user = await UserModel.where('name', 'Alice').first()

      expect(typeof user.age).toBe('number')
      expect(user.age).toBe(30)
    })

    it('aplica cast boolean: 1 → true, 0 → false', async () => {
      const alice = await UserModel.where('name', 'Alice').first()
      const charlie = await UserModel.where('name', 'Charlie').first()

      expect(alice.active).toBe(true)
      expect(charlie.active).toBe(false)
    })

    it('los getters de la clase funcionan sin @Attribute', async () => {
      const user = await UserModel.where('name', 'Alice').first()

      expect(user.label).toBe('Alice <alice@example.com>')
    })
  })

  // ─── Static query methods ─────────────────────────────────────────────────

  describe('Querying', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
    })

    it('get() retorna todos los registros', async () => {
      const users = await UserModel.get()

      expect(users).toHaveLength(3)
    })

    it('find(id) retorna la entidad por PK', async () => {
      const all = await UserModel.get()
      const user = await UserModel.find(all[0].id)

      expect(user).toBeInstanceOf(User)
      expect(user.id).toBe(all[0].id)
    })

    it('find(id) retorna null si no existe', async () => {
      expect(await UserModel.find(99999)).toBeNull()
    })

    it('first() retorna la primera entidad', async () => {
      expect(await UserModel.first()).toBeInstanceOf(User)
    })

    it('where() filtra por igualdad', async () => {
      const users = await UserModel.where('name', 'Alice').get()

      expect(users).toHaveLength(1)
      expect(users[0].name).toBe('Alice')
    })

    it('whereIn() filtra por lista', async () => {
      const users = await UserModel.whereIn('name', ['Alice', 'Bob']).get()

      expect(users).toHaveLength(2)
    })

    it('whereNotIn() excluye valores de la lista', async () => {
      const users = await UserModel.whereNotIn('name', ['Charlie']).get()

      expect(users).toHaveLength(2)
    })

    it('whereBetween() filtra por rango', async () => {
      const users = await UserModel.whereBetween('age', [25, 30]).get()

      expect(users).toHaveLength(2)
    })

    it('whereNull() y whereNotNull()', async () => {
      const nullCo = await UserModel.whereNull('countryId').get()
      const notNullCo = await UserModel.whereNotNull('countryId').get()

      expect(nullCo).toHaveLength(0)
      expect(notNullCo).toHaveLength(3)
    })

    it('orderBy() ordena correctamente', async () => {
      const users = await UserModel.orderBy('name').get()

      expect(users.map((u: any) => u.name)).toEqual(['Alice', 'Bob', 'Charlie'])
    })

    it('limit() y offset() paginan', async () => {
      const all = await UserModel.orderBy('name').get()
      const paged = await UserModel.orderBy('name').limit(2).offset(1).get()

      expect(paged).toHaveLength(2)
      expect(paged[0].name).toBe(all[1].name)
    })

    it('encadena where() consecutivos (AND implícito)', async () => {
      const users = await UserModel.where('active', 1).where('age', '>', 26).get()

      expect(users).toHaveLength(1)
      expect(users[0].name).toBe('Alice')
    })
  })

  describe('count() y paginate()', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
    })

    it('count() estático cuenta todos los registros', async () => {
      expect(await UserModel.count()).toBe(3)
    })

    it('count() respeta las condiciones encadenadas', async () => {
      expect(await UserModel.where('active', 1).count()).toBe(2)
    })

    it('count(column) resuelve nombres de campo de la entidad', async () => {
      // 'countryId' es un campo de la entidad mapeado a la columna countryId
      expect(await UserModel.query().distinct().count('countryId')).toBe(2)
    })

    it('paginate() estático retorna entidades hidratadas con metadata', async () => {
      const page = await UserModel.paginate(2, 1)

      expect(page.total).toBe(3)
      expect(page.perPage).toBe(2)
      expect(page.currentPage).toBe(1)
      expect(page.lastPage).toBe(2)
      expect(page.data).toHaveLength(2)
      expect(page.data[0]).toBeInstanceOf(User)
    })

    it('paginate() encadenado respeta where() y orden', async () => {
      const page = await UserModel.where('active', 1).orderBy('age').paginate(1, 2)

      expect(page.total).toBe(2)
      expect(page.lastPage).toBe(2)
      expect(page.currentPage).toBe(2)
      expect(page.data).toHaveLength(1)
      expect(page.data[0].name).toBe('Alice')
    })

    it('paginate() carga relaciones con with()', async () => {
      await seedRelated()
      const page = await UserModel.where('name', 'Alice').with('orders').paginate(10, 1)

      expect(page.total).toBe(1)
      expect(page.data[0].orders).toHaveLength(2)
    })

    it('paginate() retorna metadata vacía sin registros', async () => {
      const page = await UserModel.where('name', 'Zoe').paginate(5, 1)

      expect(page.total).toBe(0)
      expect(page.from).toBeNull()
      expect(page.to).toBeNull()
      expect(page.data).toHaveLength(0)
    })
  })

  // ─── save() — INSERT ──────────────────────────────────────────────────────

  describe('save() — INSERT', () => {
    it('inserta y setea el PK automáticamente', async () => {
      const user = new User() as any

      user.name = 'Dave'
      user.email = 'dave@example.com'
      user.age = 28
      user.active = 1
      await user.save()

      expect(user.id).toBeGreaterThan(0)
      const found = await UserModel.find(user.id)

      expect(found.name).toBe('Dave')
    })

    it('PKs de inserts consecutivos son distintos e incrementales', async () => {
      const u1 = new User() as any

      u1.name = 'E1'
      u1.email = 'e1@x.com'
      u1.age = 20
      u1.active = 1
      const u2 = new User() as any

      u2.name = 'E2'
      u2.email = 'e2@x.com'
      u2.age = 21
      u2.active = 1
      await u1.save()
      await u2.save()
      expect(u2.id).toBeGreaterThan(u1.id)
    })
  })

  // ─── save() — UPDATE ──────────────────────────────────────────────────────

  describe('save() — UPDATE', () => {
    it('actualiza un registro existente', async () => {
      const user = new User() as any

      user.name = 'Frank'
      user.email = 'frank@example.com'
      user.age = 40
      user.active = 1
      await user.save()
      user.name = 'Frank Updated'
      await user.save()

      const found = await UserModel.find(user.id)

      expect(found.name).toBe('Frank Updated')
    })

    it('no cambia el PK al actualizar', async () => {
      const user = new User() as any

      user.name = 'Grace'
      user.email = 'grace@example.com'
      user.age = 22
      user.active = 0
      await user.save()
      const originalId = user.id

      user.age = 23
      await user.save()
      expect(user.id).toBe(originalId)
    })
  })

  // ─── delete() ─────────────────────────────────────────────────────────────

  describe('delete()', () => {
    it('elimina el registro', async () => {
      const user = new User() as any

      user.name = 'ToDelete'
      user.email = 'del@x.com'
      user.age = 99
      user.active = 1
      await user.save()
      const id = user.id

      await user.delete()
      expect(await UserModel.find(id)).toBeNull()
    })

    it('lanza error si no tiene PK', async () => {
      const user = new User() as any

      await expect(user.delete()).rejects.toThrow()
    })
  })

  // ─── Eager loading — with() ───────────────────────────────────────────────

  describe('Eager loading — with()', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
      await seedRelated()
    })

    it('hasMany: carga órdenes del usuario', async () => {
      const users = await UserModel.where('name', 'Alice').with('orders').get()

      expect(users[0].orders).toHaveLength(2)
      expect(users[0].orders[0]).toBeInstanceOf(Order)
    })

    it('hasMany: array vacío cuando no hay relacionados', async () => {
      const users = await UserModel.where('name', 'Charlie').with('orders').get()

      expect(users[0].orders).toEqual([])
    })

    it('hasOne: carga el profile del usuario', async () => {
      const users = await UserModel.where('name', 'Alice').with('profile').get()

      expect(users[0].profile).toBeInstanceOf(Profile)
      expect(users[0].profile.bio).toBe('Alice bio')
    })

    it('hasOne: null cuando no hay relacionado', async () => {
      const users = await UserModel.where('name', 'Charlie').with('profile').get()

      expect(users[0].profile).toBeNull()
    })

    it('belongsTo: carga el country del usuario', async () => {
      const users = await UserModel.where('name', 'Alice').with('country').get()

      expect(users[0].country).toBeInstanceOf(Country)
      expect(users[0].country.code).toBe('AR')
    })

    it('carga múltiples relaciones a la vez', async () => {
      const users = await UserModel.where('name', 'Alice').with('orders', 'profile').get()

      expect(users[0].orders).toHaveLength(2)
      expect(users[0].profile).toBeInstanceOf(Profile)
    })

    it('distribuye correctamente entre todos los registros', async () => {
      const users = await UserModel.with('orders').get()
      const alice = users.find((u: any) => u.name === 'Alice')
      const bob = users.find((u: any) => u.name === 'Bob')
      const charlie = users.find((u: any) => u.name === 'Charlie')

      expect(alice.orders).toHaveLength(2)
      expect(bob.orders).toHaveLength(1)
      expect(charlie.orders).toHaveLength(0)
    })

    it('dot-notation: carga relaciones anidadas', async () => {
      const orders = await OrderModel.with('user.country').get()
      const widget = orders.find((o: any) => o.product === 'Widget')

      expect(widget.user).toBeInstanceOf(User)
      expect(widget.user.country).toBeInstanceOf(Country)
      expect(widget.user.country.code).toBe('AR')
    })

    it('hasManyThrough: orders de un country', async () => {
      const countries = await CountryModel.where('code', 'AR').with('orders').get()

      expect(countries[0].orders).toHaveLength(3) // Alice (2) + Bob (1)
    })

    it('hasOneThrough: shippingAddress de un user via profile', async () => {
      const users = await UserModel.where('name', 'Alice').with('shippingAddress').get()

      expect(users[0].shippingAddress).toBeDefined()
      expect(users[0].shippingAddress.street).toBe('123 Main St')
    })
  })

  // ─── Constrained eager loading — with({ rel: callback }) ────────────────────

  describe('Constrained eager loading — with({ rel: callback })', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
      await seedRelated()
    })

    it('hasMany: filtra los relacionados con where()', async () => {
      const users = await UserModel.with({ orders: (q) => q.where('product', 'Widget') }).get()
      const alice = users.find((u: any) => u.name === 'Alice')
      const bob = users.find((u: any) => u.name === 'Bob')

      // Alice tiene Widget; Bob tiene Doohickey → no pasa el filtro
      expect(alice.orders).toHaveLength(1)
      expect(alice.orders[0].product).toBe('Widget')
      expect(bob.orders).toHaveLength(0)
    })

    it('hasMany: filtra con condición numérica', async () => {
      // Solo órdenes con amount > 10 → Gadget (24.99); Widget (9.99) y Doohickey (4.99) quedan fuera
      const users = await UserModel.where('name', 'Alice')
        .with({ orders: (q) => q.where('amount', '>', 10) })
        .get()

      expect(users[0].orders).toHaveLength(1)
      expect(users[0].orders[0].product).toBe('Gadget')
    })

    it('hasMany: ordena los relacionados con orderBy()', async () => {
      const users = await UserModel.where('name', 'Alice')
        .with({ orders: (q) => q.orderByDesc('amount') })
        .get()
      const amounts = users[0].orders.map((o: any) => o.amount)

      expect(amounts).toEqual([24.99, 9.99])
    })

    it('hasMany: limita los relacionados con limit()', async () => {
      const users = await UserModel.where('name', 'Alice')
        .with({ orders: (q) => q.limit(1) })
        .get()

      expect(users[0].orders).toHaveLength(1)
    })

    it('belongsTo: filtra con callback (retorna null si no pasa)', async () => {
      // Todos los usuarios pertenecen a AR o BR; pedimos solo country con code 'AR'
      const users = await UserModel.with({ country: (q) => q.where('code', 'AR') })
        .orderBy('name')
        .get()
      const alice = users.find((u: any) => u.name === 'Alice')
      const charlie = users.find((u: any) => u.name === 'Charlie') // pertenece a BR

      expect(alice.country).toBeInstanceOf(Country)
      expect(alice.country.code).toBe('AR')
      expect(charlie.country).toBeNull()
    })

    it('hasManyThrough: filtra los relacionados con callback', async () => {
      // AR tiene 3 órdenes (Alice: Widget 9.99, Gadget 24.99; Bob: Doohickey 4.99)
      // Solo las que cuestan más de 10
      const countries = await CountryModel.where('code', 'AR')
        .with({ orders: (q) => q.where('amount', '>', 10) })
        .get()

      expect(countries[0].orders).toHaveLength(1)
      expect(countries[0].orders[0].product).toBe('Gadget')
    })

    it('múltiples relaciones con distintos callbacks', async () => {
      const users = await UserModel.where('name', 'Alice')
        .with({
          orders: (q) => q.where('product', 'Gadget'),
          country: (q) => q.where('code', 'AR')
        })
        .get()

      expect(users[0].orders).toHaveLength(1)
      expect(users[0].orders[0].product).toBe('Gadget')
      expect(users[0].country).toBeInstanceOf(Country)
    })

    it('mezcla relaciones con y sin callback en llamadas encadenadas', async () => {
      const users = await UserModel.where('name', 'Alice')
        .with('profile')
        .with({ orders: (q) => q.where('product', 'Widget') })
        .get()

      expect(users[0].profile).toBeInstanceOf(Profile)
      expect(users[0].orders).toHaveLength(1)
      expect(users[0].orders[0].product).toBe('Widget')
    })

    it('dot-notation con constraint en la relación anidada', async () => {
      // Cargamos orders.user pero solo users con age > 26 (Alice 30; Bob 25 queda fuera)
      const orders = await OrderModel.with({ user: (q) => q.where('age', '>', 26) })
        .orderBy('product')
        .get()
      const widget = orders.find((o: any) => o.product === 'Widget') // de Alice (age 30)
      const doohickey = orders.find((o: any) => o.product === 'Doohickey') // de Bob (age 25)

      expect(widget.user).toBeInstanceOf(User)
      expect(doohickey.user).toBeNull()
    })
  })

  // ─── joinRelationship ────────────────────────────────────────────────────

  describe('joinRelationship', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
      await seedRelated()
    })

    it('innerJoinRelationship() retorna solo registros con relación', async () => {
      const users = await UserModel.innerJoinRelationship('orders').select('users.id', 'users.name').distinct().get()
      const names = users.map((u: any) => u.name).sort()

      expect(names).toEqual(['Alice', 'Bob'])
    })

    it('leftJoinRelationship() incluye todos los registros', async () => {
      const users = await UserModel.leftJoinRelationship('orders').select('users.id', 'users.name').distinct().get()

      expect(users).toHaveLength(3)
    })

    it('joinRelationship() es alias de innerJoinRelationship()', async () => {
      const users = await UserModel.joinRelationship('orders').select('users.id', 'users.name').distinct().get()

      expect(users.map((u: any) => u.name).sort()).toEqual(['Alice', 'Bob'])
    })

    it('joinRelationship() encadenado desde where()', async () => {
      const users = await UserModel.where('active', 1)
        .leftJoinRelationship('profile')
        .select('users.id', 'users.name')
        .get()

      expect(users.length).toBeGreaterThanOrEqual(2)
    })

    it('lanza error si la relación no existe', () => {
      expect(() => UserModel.joinRelationship('nonexistent')).toThrow()
    })
  })

  // ─── whereHas / orWhereHas ────────────────────────────────────────────────

  describe('whereHas / orWhereHas', () => {
    beforeEach(async () => {
      await seedCountries()
      await seedUsers()
      await seedRelated()
    })

    it('whereHas(hasMany) — devuelve solo los que tienen relacionados', async () => {
      const users = await UserModel.whereHas('orders').orderBy('name').get()
      const names = users.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Bob'])
    })

    it('whereHas(hasMany) con callback — filtra por condición en el relacionado', async () => {
      const users = await UserModel.whereHas('orders', (q) => q.where('product', 'Widget')).get()

      expect(users).toHaveLength(1)
      expect(users[0].name).toBe('Alice')
    })

    it('whereHas(hasMany) con callback y binding numérico', async () => {
      // Bob solo tiene Doohickey (4.99); Alice tiene Widget (9.99) y Gadget (24.99)
      const users = await UserModel.whereHas('orders', (q) => q.where('amount', '>', 10)).get()

      expect(users).toHaveLength(1)
      expect(users[0].name).toBe('Alice')
    })

    it('whereHas(hasOne) — devuelve solo los que tienen el relacionado', async () => {
      const users = await UserModel.whereHas('profile').orderBy('name').get()
      const names = users.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Bob'])
    })

    it('whereHas(belongsTo) — devuelve los que tienen la FK satisfecha', async () => {
      // Los 3 usuarios tienen país asignado
      const users = await UserModel.whereHas('country').get()

      expect(users).toHaveLength(3)
    })

    it('whereHas(hasManyThrough) — filtra entidades que tienen relacionados a través', async () => {
      // AR tiene órdenes (Alice + Bob), BR (Charlie) no tiene ninguna
      const countries = await CountryModel.whereHas('orders').get()

      expect(countries).toHaveLength(1)
      expect(countries[0].code).toBe('AR')
    })

    it('whereHas devuelve vacío cuando ningún registro tiene relacionados', async () => {
      // Charlie no tiene órdenes; queremos solo los que tengan producto 'Nonexistent'
      const users = await UserModel.whereHas('orders', (q) => q.where('product', 'Nonexistent')).get()

      expect(users).toHaveLength(0)
    })

    it('orWhereHas — combina con OR correctamente', async () => {
      // Charlie no tiene órdenes → no entra por whereHas; Alice sí tiene Widget → entra
      // Charlie entra por where('name', 'Charlie')
      const users = await UserModel.where('name', 'Charlie')
        .orWhereHas('orders', (q) => q.where('product', 'Widget'))
        .orderBy('name')
        .get()
      const names = users.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Charlie'])
    })

    it('where + whereHas encadenados (AND implícito)', async () => {
      // active = 1 AND has orders → Alice y Bob están activos y tienen órdenes
      const users = await UserModel.where('active', 1).whereHas('orders').orderBy('name').get()
      const names = users.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Bob'])
    })

    it('whereHas encadenado después de otro whereHas', async () => {
      // Usuarios con orders Y con profile → Alice y Bob
      const users = await UserModel.whereHas('orders').whereHas('profile').orderBy('name').get()
      const names = users.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Bob'])
    })

    it('lanza error si la relación no existe', () => {
      expect(() => UserModel.whereHas('nonexistent')).toThrow('Relationship "nonexistent" is not defined on users')
    })

    // ── Regression: orWhere dentro del callback de whereHas ──────────────────
    // Bug: la condición correlacionada (orders.userId = users.id) se añadía al
    // mismo nivel que las condiciones del usuario. Con precedencia AND > OR el SQL
    // quedaba: product = ? OR amount > ? AND orders.userId = users.id
    // lo que equivale a:
    //   product = ? OR (amount > ? AND orders.userId = users.id)
    // haciendo que la rama OR pudiera devolver órdenes de cualquier usuario.

    it('whereHas con orWhere en el callback aplica la correlación a todas las ramas', async () => {
      // Alice tiene Widget (9.99) y Gadget (24.99); Bob tiene Doohickey (4.99)
      // Queremos usuarios que tengan al menos una orden con product='Widget' OR amount>10
      // → Alice cumple ambas condiciones, Bob no cumple ninguna
      const users = await UserModel.whereHas('orders', (q) => q.where('product', 'Widget').orWhere('amount', '>', 10))
        .orderBy('name')
        .get()
      const names = users.map((u: any) => u.name)

      expect(names).toEqual(['Alice'])
    })

    // ── Regression: whereHas + orWhere anidado + paginate ────────────────────
    // Bug: el subquery de EXISTS se pre-compilaba con placeholders de Postgres
    // ($1, $2…) relativos a un statement vacío. Al embeber en el outer query el
    // count() y el get() producían posiciones $N incorrectas / con saltos que
    // chocaban en el prepared statement.

    it('whereHas + orWhere externo + paginate() retorna totales y datos correctos', async () => {
      // Alice: active=1 y tiene órdenes  → entra por whereHas
      // Bob:   active=1 y tiene órdenes  → entra por whereHas
      // Charlie: active=0, sin órdenes  → entra por orWhere('name', 'Charlie')
      const page = await UserModel.whereHas('orders').orWhere('name', 'Charlie').orderBy('name').paginate(10, 1)

      expect(page.total).toBe(3)
      expect(page.data).toHaveLength(3)
      const names = page.data.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Bob', 'Charlie'])
    })

    it('whereHas con callback + orWhere externo + paginate() respeta ambas condiciones', async () => {
      // whereHas filtra usuarios con orden de amount > 10 → solo Alice (Gadget 24.99)
      // orWhere agrega a Charlie aunque no tenga órdenes
      const page = await UserModel.whereHas('orders', (q) => q.where('amount', '>', 10))
        .orWhere('name', 'Charlie')
        .orderBy('name')
        .paginate(10, 1)

      expect(page.total).toBe(2)
      expect(page.data).toHaveLength(2)
      const names = page.data.map((u: any) => u.name)

      expect(names).toEqual(['Alice', 'Charlie'])
    })
  })

  // ─── columnName — renombrado de columnas ──────────────────────────────────

  describe('columnName — renombrado de columnas', () => {
    beforeAll(async () => {
      await source.execute(`
        CREATE TABLE employees (
          employee_id INTEGER PRIMARY KEY AUTOINCREMENT,
          first_name  TEXT    NOT NULL,
          is_active   INTEGER NOT NULL DEFAULT 1,
          email       TEXT    NOT NULL
        )
      `)
    })

    beforeEach(async () => {
      await source.execute('DELETE FROM employees')
    })

    it('registra el columnsMap (propiedad → columna DB)', () => {
      expect(Repository.get(EmployeeModel).columnsMap).toEqual({
        id: 'employee_id',
        firstName: 'first_name',
        isActive: 'is_active',
        email: 'email'
      })
    })

    it('el primaryKey usa el columnName de la PK', () => {
      expect(Repository.get(EmployeeModel).primaryKey).toBe('employee_id')
    })

    it('fields conserva los nombres de propiedad', () => {
      expect(Repository.get(EmployeeModel).fields).toEqual(['id', 'firstName', 'isActive', 'email'])
    })

    it('hidrata propiedades desde columnas renombradas (con casts)', async () => {
      await source.execute(`INSERT INTO employees (first_name, is_active, email) VALUES ('Alice', 1, 'alice@x.com')`)

      const employee = await EmployeeModel.first()

      expect(employee).toBeInstanceOf(Employee)
      expect(employee.id).toBeGreaterThan(0)
      expect(employee.firstName).toBe('Alice')
      expect(employee.isActive).toBe(true)
      expect(employee.email).toBe('alice@x.com')
    })

    it('find(id) busca por la columna renombrada de la PK', async () => {
      await source.execute(`INSERT INTO employees (first_name, is_active, email) VALUES ('Bob', 0, 'bob@x.com')`)
      const row = await source.table('employees').first()
      const employee = await EmployeeModel.find(row!.employee_id)

      expect(employee).not.toBeNull()
      expect(employee.firstName).toBe('Bob')
      expect(employee.isActive).toBe(false)
    })

    it('where() filtra usando el nombre de columna de la DB', async () => {
      await source.execute(`INSERT INTO employees (first_name, is_active, email) VALUES ('Carol', 1, 'carol@x.com')`)

      const employees = await EmployeeModel.where('first_name', 'Carol').get()

      expect(employees).toHaveLength(1)
      expect(employees[0].firstName).toBe('Carol')
    })

    it('INSERT escribe en las columnas renombradas y setea la PK en la propiedad', async () => {
      const employee = new Employee() as any

      employee.firstName = 'Dave'
      employee.isActive = true
      employee.email = 'dave@x.com'
      await employee.save()

      expect(employee.id).toBeGreaterThan(0)
      const row = await source.table('employees').where('employee_id', employee.id).first()

      expect(row!.first_name).toBe('Dave')
      expect(row!.is_active).toBe(1)
      expect(row!.email).toBe('dave@x.com')
    })

    it('UPDATE usa la columna renombrada de la PK y no la duplica en el SET', async () => {
      const employee = new Employee() as any

      employee.firstName = 'Eve'
      employee.isActive = true
      employee.email = 'eve@x.com'
      await employee.save()
      const originalId = employee.id

      employee.firstName = 'Eve Updated'
      employee.isActive = false
      await employee.save()

      expect(employee.id).toBe(originalId)
      const row = await source.table('employees').where('employee_id', originalId).first()

      expect(row!.first_name).toBe('Eve Updated')
      expect(row!.is_active).toBe(0)
    })

    it('DELETE elimina por la columna renombrada de la PK', async () => {
      const employee = new Employee() as any

      employee.firstName = 'Frank'
      employee.isActive = true
      employee.email = 'frank@x.com'
      await employee.save()
      const id = employee.id

      await employee.delete()
      expect(await EmployeeModel.find(id)).toBeNull()
    })
  })

  // ─── Resolución de nombres de propiedad → columna en queries ──────────────

  describe('resolución de propiedades en queries', () => {
    beforeEach(async () => {
      await source.execute('DELETE FROM employees')
      await source.execute(`
        INSERT INTO employees (first_name, is_active, email) VALUES
          ('Luis', 1, 'luis@x.com'),
          ('Ana', 0, 'ana@x.com'),
          ('Zoe', 1, 'zoe@x.com')
      `)
    })

    it('where() acepta el nombre de propiedad', async () => {
      const employee = await EmployeeModel.where('firstName', 'Luis').first()

      expect(employee).not.toBeNull()
      expect(employee.firstName).toBe('Luis')
    })

    it('where() sigue aceptando el nombre de columna de la DB', async () => {
      const employee = await EmployeeModel.where('first_name', 'Luis').first()

      expect(employee).not.toBeNull()
      expect(employee.firstName).toBe('Luis')
    })

    it('where() con operador acepta el nombre de propiedad', async () => {
      const employees = await EmployeeModel.where('isActive', '=', 1).get()

      expect(employees).toHaveLength(2)
    })

    it('where() resuelve propiedades calificadas con la tabla de la entidad', async () => {
      const employee = await EmployeeModel.where('employees.firstName', 'Ana').first()

      expect(employee).not.toBeNull()
      expect(employee.firstName).toBe('Ana')
    })

    it('orderBy() acepta el nombre de propiedad', async () => {
      const employees = await EmployeeModel.orderBy('firstName', OrderByDirection.DESC).get()

      expect(employees.map((e: any) => e.firstName)).toEqual(['Zoe', 'Luis', 'Ana'])
    })

    it('whereIn() acepta el nombre de propiedad', async () => {
      const employees = await EmployeeModel.whereIn('firstName', ['Luis', 'Zoe']).get()

      expect(employees).toHaveLength(2)
    })

    it('whereLike() acepta el nombre de propiedad', async () => {
      const employees = await EmployeeModel.whereLike('firstName', 'L%').get()

      expect(employees).toHaveLength(1)
      expect(employees[0].firstName).toBe('Luis')
    })

    it('orWhere() acepta el nombre de propiedad', async () => {
      const employees = await EmployeeModel.where('firstName', 'Luis').orWhere('firstName', 'Ana').get()

      expect(employees).toHaveLength(2)
    })

    it('select() acepta nombres de propiedad', async () => {
      const employee = await EmployeeModel.select('firstName').where('firstName', 'Luis').first()

      expect(employee.firstName).toBe('Luis')
      expect(employee.email).toBeUndefined()
    })

    it('groupBy() acepta el nombre de propiedad', async () => {
      const employees = await EmployeeModel.select('isActive').groupBy('isActive').get()

      expect(employees).toHaveLength(2)
    })

    it('where(callback) resuelve propiedades dentro del grupo', async () => {
      const employees = await EmployeeModel.where((group: any) =>
        group.where('firstName', 'Luis').orWhere('firstName', 'Ana')
      ).get()

      expect(employees).toHaveLength(2)
    })

    it('where(callback) resuelve propiedades en grupos anidados', async () => {
      const employees = await EmployeeModel.where((group: any) =>
        group.where('isActive', 1).where((inner: any) => inner.where('firstName', 'Luis').orWhere('firstName', 'Zoe'))
      ).get()

      expect(employees).toHaveLength(2)
    })

    it('where(callback) resuelve métodos de conveniencia del grupo', async () => {
      const employees = await EmployeeModel.where((group: any) =>
        group.whereIn('firstName', ['Luis', 'Ana']).whereLike('firstName', 'L%')
      ).get()

      expect(employees).toHaveLength(1)
      expect(employees[0].firstName).toBe('Luis')
    })

    it('where(condition) resuelve propiedades en condiciones directas', async () => {
      const employees = await EmployeeModel.where({ field: 'firstName', operator: '=', value: 'Ana' }).get()

      expect(employees).toHaveLength(1)
      expect(employees[0].firstName).toBe('Ana')
    })
  })
})
