import { BaseEntity, Column, DB, Entity, HasManyInArray, SqliteDataSource } from '../src'

/**
 * @HasManyInArray — a many-relationship resolved through an array of related
 * keys stored on the owning row (e.g. PostgreSQL INTEGER[] / SQLite JSON TEXT).
 * Eager loading preserves the array order; whereHas correlates via array
 * containment.
 */

@Entity({ table: 'users' })
class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string
}

@Entity({ table: 'teams' })
class Team extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'array' })
  memberIds!: number[]

  @HasManyInArray(() => User, 'memberIds')
  members?: User[]
}

let source: SqliteDataSource

beforeAll(async () => {
  source = new SqliteDataSource()

  await source.execute(`CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL)`)
  await source.execute(
    `CREATE TABLE teams (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, memberIds TEXT NOT NULL DEFAULT '[]')`
  )

  DB.register(source)

  await DB.table('users').insert({ name: 'Alice' }) // id 1
  await DB.table('users').insert({ name: 'Bob' }) // id 2
  await DB.table('users').insert({ name: 'Carol' }) // id 3

  await DB.table('teams').insert({ name: 'Team A', memberIds: JSON.stringify([3, 1]) })
  await DB.table('teams').insert({ name: 'Team B', memberIds: JSON.stringify([2]) })
  await DB.table('teams').insert({ name: 'Team C', memberIds: JSON.stringify([]) })
})

afterAll(async () => {
  await source.close()
})

describe('@HasManyInArray', () => {
  it('eager-loads the related rows preserving the array order', async () => {
    const teams = await Team.with('members').orderBy('id').get()

    expect(teams[0].members?.map((m) => m.name)).toEqual(['Carol', 'Alice'])
    expect(teams[1].members?.map((m) => m.name)).toEqual(['Bob'])
    expect(teams[2].members).toEqual([])
  })

  it('resolves the relation for a single loaded entity', async () => {
    const team = await Team.with('members').where('id', 1).first()

    expect(team?.members?.map((m) => m.id)).toEqual([3, 1])
  })

  it('whereHas keeps only owners that have at least one related row', async () => {
    const teams = await Team.whereHas('members').orderBy('id').get()

    expect(teams.map((t) => t.name)).toEqual(['Team A', 'Team B'])
  })

  it('whereHas with a callback filters by the related row', async () => {
    const teams = await Team.whereHas('members', (q) => q.where('name', 'Bob')).get()

    expect(teams.map((t) => t.name)).toEqual(['Team B'])
  })
})
