import { BaseEntity, BelongsTo, Column, DB, Entity, HasMany, Repository, SqliteDataSource, VirtualColumn } from '../src'

// ─── Model definitions ────────────────────────────────────────────────────────

@Entity({ table: 'authors' })
class Author extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'date' })
  bornAt!: Date

  @HasMany(() => Post, 'authorId')
  posts?: Post[]
}

@Entity({ table: 'posts' })
class Post extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  title!: string

  @Column()
  authorId!: number

  @Column({ cast: 'date' })
  publishedAt!: Date

  @BelongsTo(() => Author, 'authorId')
  author?: Author

  @VirtualColumn()
  get slug(): string {
    return this.title.toLowerCase().replace(/\s+/g, '-')
  }
}

// Plain entity — does NOT extend BaseEntity. Exercises the Repository facade.
@Entity({ table: 'countries' })
class Country {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'date' })
  foundedAt!: Date
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('toJSON / fromJSON', () => {
  const source = new SqliteDataSource()

  beforeAll(async () => {
    DB.register(source)
    await source.execute('CREATE TABLE authors (id INTEGER PRIMARY KEY, name TEXT, bornAt TEXT)')
    await source.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, authorId INTEGER, publishedAt TEXT)')
    await source.execute('CREATE TABLE countries (id INTEGER PRIMARY KEY, name TEXT, foundedAt TEXT)')

    const author = new Author()

    author.name = 'Borges'
    author.bornAt = new Date('1899-08-24T00:00:00.000Z')
    await author.save()

    const post = new Post()

    post.title = 'El Aleph'
    post.authorId = author.id
    post.publishedAt = new Date('1945-09-01T12:30:00.000Z')
    await post.save()
  })

  afterAll(async () => {
    await source.close()
  })

  test('toJSON converts Date fields to ISO strings and includes getters', async () => {
    const post = await Post.find(1)
    const json = post!.toJSON()

    expect(json).toEqual({
      id: 1,
      title: 'El Aleph',
      authorId: 1,
      publishedAt: '1945-09-01T12:30:00.000Z',
      slug: 'el-aleph'
    })
    // Genuinely JSON-safe: survives a stringify/parse round-trip unchanged.
    expect(JSON.parse(JSON.stringify(json))).toEqual(json)
  })

  test('fromJSON re-hydrates Date fields back into Date instances', () => {
    const post = Post.fromJSON({
      id: 1,
      title: 'El Aleph',
      authorId: 1,
      publishedAt: '1945-09-01T12:30:00.000Z'
    })

    expect(post).toBeInstanceOf(Post)
    expect(post.publishedAt).toBeInstanceOf(Date)
    expect(post.publishedAt.toISOString()).toBe('1945-09-01T12:30:00.000Z')
    // Computed getter still works on the re-hydrated instance.
    expect(post.slug).toBe('el-aleph')
  })

  test('full round-trip through JSON preserves data and types', async () => {
    const original = await Post.find(1)
    const restored = Post.fromJSON(JSON.parse(JSON.stringify(original)))

    expect(restored).toBeInstanceOf(Post)
    expect(restored.publishedAt).toBeInstanceOf(Date)
    expect(restored.publishedAt.getTime()).toBe(original!.publishedAt.getTime())
    expect(restored.title).toBe(original!.title)
  })

  test('toJSON serializes loaded relationships recursively (hasMany)', async () => {
    const author = await Author.with('posts').first()
    const json = author!.toJSON()

    expect(json.bornAt).toBe('1899-08-24T00:00:00.000Z')
    expect(json.posts).toHaveLength(1)
    expect(json.posts[0]).toEqual({
      id: 1,
      title: 'El Aleph',
      authorId: 1,
      publishedAt: '1945-09-01T12:30:00.000Z',
      slug: 'el-aleph'
    })
  })

  test('fromJSON re-hydrates nested relationships recursively', () => {
    const author = Author.fromJSON({
      id: 1,
      name: 'Borges',
      bornAt: '1899-08-24T00:00:00.000Z',
      posts: [
        {
          id: 1,
          title: 'El Aleph',
          authorId: 1,
          publishedAt: '1945-09-01T12:30:00.000Z'
        }
      ]
    })

    expect(author).toBeInstanceOf(Author)
    expect(author.bornAt).toBeInstanceOf(Date)
    expect(author.posts).toHaveLength(1)
    expect(author.posts![0]).toBeInstanceOf(Post)
    expect(author.posts![0].publishedAt).toBeInstanceOf(Date)
    expect(author.posts![0].slug).toBe('el-aleph')
  })

  test('belongsTo relationship round-trips both ways', async () => {
    const post = await Post.with('author').first()
    const json = post!.toJSON()

    expect(json.author).toEqual({
      id: 1,
      name: 'Borges',
      bornAt: '1899-08-24T00:00:00.000Z'
    })

    const restored = Post.fromJSON(json)

    expect(restored.author).toBeInstanceOf(Author)
    expect(restored.author!.bornAt).toBeInstanceOf(Date)
  })

  test('Repository facade exposes toJSON / fromJSON for plain (non-BaseEntity) entities', () => {
    const country = new Country()

    country.id = 5
    country.name = 'Argentina'
    country.foundedAt = new Date('1816-07-09T00:00:00.000Z')

    const json = Repository.get(Country).toJSON(country)

    expect(json).toEqual({
      id: 5,
      name: 'Argentina',
      foundedAt: '1816-07-09T00:00:00.000Z'
    })

    const restored = Repository.get(Country).fromJSON(json)

    expect(restored).toBeInstanceOf(Country)
    expect(restored.foundedAt).toBeInstanceOf(Date)
    expect(restored.foundedAt.getTime()).toBe(country.foundedAt.getTime())
  })

  test('fromJSON revives ISO date strings even without a declared cast', () => {
    // `createdAt` is not a declared column/cast — the ISO heuristic still applies.
    const restored: any = Repository.get(Country).fromJSON({
      id: 9,
      name: 'Chile',
      foundedAt: '1810-09-18T00:00:00.000Z',
      createdAt: '2024-01-02T03:04:05.000Z'
    })

    expect(restored.createdAt).toBeInstanceOf(Date)
    expect((restored.createdAt as Date).toISOString()).toBe('2024-01-02T03:04:05.000Z')
  })
})
