import { BaseEntity, BelongsTo, Column, DB, Entity, HasMany, Repository, Serializable, SqliteDataSource } from '../src'

// ─── Model definitions ────────────────────────────────────────────────────────

@Entity({ table: 'authors' })
class Author extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'date' })
  bornAt!: Date

  @HasMany(() => Post, 'authorId')
  posts?: Post[]
}

@Entity({ table: 'posts' })
class Post extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  title!: string

  @Column()
  authorId!: number

  @Column({ cast: 'date' })
  publishedAt!: Date

  @BelongsTo(() => Author, 'authorId')
  author?: Author

  @Serializable()
  get slug(): string {
    return this.title.toLowerCase().replace(/\s+/g, '-')
  }
}

// Entity with @Serializable(false) to exclude fields and relationships from serialization.
@Entity({ table: 'products' })
class Product extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Serializable(false)
  @Column()
  internalCode!: string

  @BelongsTo(() => Author, 'authorId')
  author?: Author

  @Serializable(false)
  @BelongsTo(() => Post, 'postId')
  post?: Post

  @Serializable()
  get displayName(): string {
    return `[${this.internalCode}] ${this.name}`
  }
}

// Plain entity — does NOT extend BaseEntity. Exercises the Repository facade.
@Entity({ table: 'countries' })
class Country {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'date' })
  foundedAt!: Date
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('toJSON / fromJSON', () => {
  const source = new SqliteDataSource()

  beforeAll(async () => {
    DB.register(source)
    await source.execute('CREATE TABLE authors (id INTEGER PRIMARY KEY, name TEXT, bornAt TEXT)')
    await source.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT, authorId INTEGER, publishedAt TEXT)')
    await source.execute('CREATE TABLE countries (id INTEGER PRIMARY KEY, name TEXT, foundedAt TEXT)')

    const author = new Author()

    author.name = 'Borges'
    author.bornAt = new Date('1899-08-24T00:00:00.000Z')
    await author.save()

    const post = new Post()

    post.title = 'El Aleph'
    post.authorId = author.id
    post.publishedAt = new Date('1945-09-01T12:30:00.000Z')
    await post.save()
  })

  afterAll(async () => {
    await source.close()
  })

  test('toJSON converts Date fields to ISO strings and includes getters', async () => {
    const post = await Post.find(1)
    const json = post!.toJSON()

    expect(json).toEqual({
      id: 1,
      title: 'El Aleph',
      authorId: 1,
      publishedAt: '1945-09-01T12:30:00.000Z',
      slug: 'el-aleph'
    })
    // Genuinely JSON-safe: survives a stringify/parse round-trip unchanged.
    expect(JSON.parse(JSON.stringify(json))).toEqual(json)
  })

  test('fromJSON re-hydrates Date fields back into Date instances', () => {
    const post = Post.fromJSON({
      id: 1,
      title: 'El Aleph',
      authorId: 1,
      publishedAt: '1945-09-01T12:30:00.000Z'
    })

    expect(post).toBeInstanceOf(Post)
    expect(post.publishedAt).toBeInstanceOf(Date)
    expect(post.publishedAt.toISOString()).toBe('1945-09-01T12:30:00.000Z')
    // Computed getter still works on the re-hydrated instance.
    expect(post.slug).toBe('el-aleph')
  })

  test('full round-trip through JSON preserves data and types', async () => {
    const original = await Post.find(1)
    const restored = Post.fromJSON(JSON.parse(JSON.stringify(original)))

    expect(restored).toBeInstanceOf(Post)
    expect(restored.publishedAt).toBeInstanceOf(Date)
    expect(restored.publishedAt.getTime()).toBe(original!.publishedAt.getTime())
    expect(restored.title).toBe(original!.title)
  })

  test('toJSON serializes loaded relationships recursively (hasMany)', async () => {
    const author = await Author.with('posts').first()
    const json = author!.toJSON()

    expect(json.bornAt).toBe('1899-08-24T00:00:00.000Z')
    expect(json.posts).toHaveLength(1)
    expect(json.posts[0]).toEqual({
      id: 1,
      title: 'El Aleph',
      authorId: 1,
      publishedAt: '1945-09-01T12:30:00.000Z',
      slug: 'el-aleph'
    })
  })

  test('fromJSON re-hydrates nested relationships recursively', () => {
    const author = Author.fromJSON({
      id: 1,
      name: 'Borges',
      bornAt: '1899-08-24T00:00:00.000Z',
      posts: [
        {
          id: 1,
          title: 'El Aleph',
          authorId: 1,
          publishedAt: '1945-09-01T12:30:00.000Z'
        }
      ]
    })

    expect(author).toBeInstanceOf(Author)
    expect(author.bornAt).toBeInstanceOf(Date)
    expect(author.posts).toHaveLength(1)
    expect(author.posts![0]).toBeInstanceOf(Post)
    expect(author.posts![0].publishedAt).toBeInstanceOf(Date)
    expect(author.posts![0].slug).toBe('el-aleph')
  })

  test('belongsTo relationship round-trips both ways', async () => {
    const post = await Post.with('author').first()
    const json = post!.toJSON()

    expect(json.author).toEqual({
      id: 1,
      name: 'Borges',
      bornAt: '1899-08-24T00:00:00.000Z'
    })

    const restored = Post.fromJSON(json)

    expect(restored.author).toBeInstanceOf(Author)
    expect(restored.author!.bornAt).toBeInstanceOf(Date)
  })

  test('Repository facade exposes toJSON / fromJSON for plain (non-BaseEntity) entities', () => {
    const country = new Country()

    country.id = 5
    country.name = 'Argentina'
    country.foundedAt = new Date('1816-07-09T00:00:00.000Z')

    const json = Repository.get(Country).toJSON(country)

    expect(json).toEqual({
      id: 5,
      name: 'Argentina',
      foundedAt: '1816-07-09T00:00:00.000Z'
    })

    const restored = Repository.get(Country).fromJSON(json)

    expect(restored).toBeInstanceOf(Country)
    expect(restored.foundedAt).toBeInstanceOf(Date)
    expect(restored.foundedAt.getTime()).toBe(country.foundedAt.getTime())
  })

  test('fromJSON revives ISO date strings even without a declared cast', () => {
    // `createdAt` is not a declared column/cast — the ISO heuristic still applies.
    const restored: any = Repository.get(Country).fromJSON({
      id: 9,
      name: 'Chile',
      foundedAt: '1810-09-18T00:00:00.000Z',
      createdAt: '2024-01-02T03:04:05.000Z'
    })

    expect(restored.createdAt).toBeInstanceOf(Date)
    expect((restored.createdAt as Date).toISOString()).toBe('2024-01-02T03:04:05.000Z')
  })
})

describe('@Serializable decorator', () => {
  test('@Serializable() includes a getter in toJSON', () => {
    const post = new Post()

    post.id = 1
    post.title = 'El Aleph'
    post.authorId = 1
    post.publishedAt = new Date('1945-09-01T12:30:00Z')

    const json = post.toJSON()

    expect(json.slug).toBe('el-aleph')
  })

  test('@Serializable(false) excludes a column from toJSON', () => {
    const product = new Product()

    product.id = 1
    product.name = 'Widget'
    product.internalCode = 'WDG-001'

    const json = product.toJSON()

    expect(json.id).toBe(1)
    expect(json.name).toBe('Widget')
    expect(json.internalCode).toBeUndefined()
  })

  test('@Serializable(false) excludes a loaded relationship from toJSON', () => {
    const author = new Author()

    author.id = 1
    author.name = 'Borges'
    author.bornAt = new Date('1899-08-24T00:00:00Z')

    const post = new Post()

    post.id = 10
    post.title = 'Ficciones'
    post.authorId = 1
    post.publishedAt = new Date('1944-01-01T00:00:00Z')

    const product = new Product()

    product.id = 2
    product.name = 'Widget'
    product.internalCode = 'WDG-002'
    ;(product as any).author = author
    ;(product as any).post = post

    const json = product.toJSON()

    // author relationship should be serialized
    expect(json.author).toBeDefined()
    expect(json.author.name).toBe('Borges')
    // post relationship should be excluded
    expect(json.post).toBeUndefined()
  })

  test('@Serializable() getter is included even when the underlying fields are excluded', () => {
    const product = new Product()

    product.id = 1
    product.name = 'Gadget'
    product.internalCode = 'GDG-999'

    const json = product.toJSON()

    // internalCode column excluded, but displayName getter that uses it is included
    expect(json.internalCode).toBeUndefined()
    expect(json.displayName).toBe('[GDG-999] Gadget')
  })
})
