import { BaseEntity, Column, DataConnection, DB, Entity, SqliteDataSource } from '../src'

// ─── Model ───────────────────────────────────────────────────────────────────

@Entity({ table: 'accounts' })
class Account extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column({ cast: 'number' })
  balance!: number
}

describe('Transactions — entity operations share a connection and commit atomically', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE accounts (
        id      INTEGER PRIMARY KEY AUTOINCREMENT,
        name    TEXT    NOT NULL,
        balance INTEGER NOT NULL DEFAULT 0
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM accounts')
  })

  // ─── Commit ────────────────────────────────────────────────────────────────

  test('commits every entity write made inside the callback', async () => {
    await DB.transaction(async () => {
      const a = new Account()

      a.name = 'Ada'
      a.balance = 100
      await a.save()

      await Account.insert([
        { name: 'Bob', balance: 50 },
        { name: 'Cid', balance: 25 }
      ])
    })

    const accounts = await Account.orderBy('id').get()

    expect(accounts.map((a) => a.name)).toEqual(['Ada', 'Bob', 'Cid'])
    expect(await Account.count()).toBe(3)
  })

  test('returns the value produced by the callback', async () => {
    const result = await DB.transaction(async () => {
      const a = new Account()

      a.name = 'Ada'
      a.balance = 100
      await a.save()

      return a.id
    })

    expect(typeof result).toBe('number')
    expect(await Account.find(result)).not.toBeNull()
  })

  test('save() writes the generated id back inside the transaction', async () => {
    let idInsideTx: number | undefined

    await DB.transaction(async () => {
      const a = new Account()

      a.name = 'Ada'
      a.balance = 10
      await a.save()
      idInsideTx = a.id
      // The row is visible to reads made within the same transaction.
      expect(await Account.count()).toBe(1)
    })

    expect(idInsideTx).toBeGreaterThan(0)
    const persisted = await Account.find(idInsideTx!)

    expect(persisted?.name).toBe('Ada')
  })

  // ─── Rollback ────────────────────────────────────────────────────────────────

  test('rolls back every entity write when the callback throws, and re-throws', async () => {
    // A pre-existing, already-committed row must survive the rolled-back tx.
    const seed = new Account()

    seed.name = 'Seed'
    seed.balance = 1
    await seed.save()

    await expect(
      DB.transaction(async () => {
        const a = new Account()

        a.name = 'DoomedSave'
        a.balance = 100
        await a.save()

        await Account.insert([{ name: 'DoomedInsert', balance: 5 }])

        throw new Error('boom')
      })
    ).rejects.toThrow('boom')

    const names = (await Account.get()).map((a) => a.name)

    expect(names).toEqual(['Seed'])
    expect(await Account.count()).toBe(1)
  })

  test('a delete made inside a rolled-back transaction is undone', async () => {
    const a = new Account()

    a.name = 'Keep'
    a.balance = 1
    await a.save()

    await expect(
      DB.transaction(async () => {
        await a.delete()
        expect(await Account.count()).toBe(0)
        throw new Error('boom')
      })
    ).rejects.toThrow('boom')

    expect(await Account.count()).toBe(1)
    expect((await Account.first())?.name).toBe('Keep')
  })

  // ─── Connection routing ──────────────────────────────────────────────────────

  test('routes operations through the transaction connection (active connection)', async () => {
    expect(source.getActiveConnection()).toBeUndefined()

    await DB.transaction(async (tx) => {
      // Inside the callback the source exposes exactly the transaction connection.
      expect(source.getActiveConnection()).toBe(tx)
      expect(tx).toBeInstanceOf(DataConnection)
    })

    // The context is cleared once the transaction settles.
    expect(source.getActiveConnection()).toBeUndefined()
  })

  test('raw DB.execute / DB.query also participate in the active transaction', async () => {
    await expect(
      DB.transaction(async () => {
        await DB.execute('INSERT INTO accounts (name, balance) VALUES (?, ?)', ['Raw', 7])
        const rows = await DB.query('SELECT COUNT(*) AS c FROM accounts')

        expect(Number(rows[0].c)).toBe(1)
        throw new Error('boom')
      })
    ).rejects.toThrow('boom')

    expect(await Account.count()).toBe(0)
  })

  // ─── Nesting ──────────────────────────────────────────────────────────────────

  test('nested transactions join the outer one (same connection, single commit)', async () => {
    await DB.transaction(async (outer) => {
      const a = new Account()

      a.name = 'Outer'
      a.balance = 1
      await a.save()

      await DB.transaction(async (inner) => {
        // The inner call must reuse the outer connection, not open a new one.
        expect(inner).toBe(outer)

        await Account.insert([{ name: 'Inner', balance: 2 }])
      })
    })

    expect((await Account.orderBy('id').get()).map((a) => a.name)).toEqual(['Outer', 'Inner'])
  })

  test('a throw in a joined nested transaction rolls back the whole unit of work', async () => {
    await expect(
      DB.transaction(async () => {
        const a = new Account()

        a.name = 'Outer'
        a.balance = 1
        await a.save()

        await DB.transaction(async () => {
          await Account.insert([{ name: 'Inner', balance: 2 }])
          throw new Error('inner-boom')
        })
      })
    ).rejects.toThrow('inner-boom')

    expect(await Account.count()).toBe(0)
  })
})
