import { BaseEntity, Column, DB, Entity, SqliteDataSource } from '../src'

// ─── Model ───────────────────────────────────────────────────────────────────

@Entity({ table: 'player_statistics' })
class PlayerStatistics extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  playerId!: number

  @Column({ cast: 'number' })
  points!: number

  @Column({ cast: 'number' })
  matches!: number

  @Column({ cast: 'date' })
  updatedAt!: Date
}

describe('Upsert — insert or update on conflict', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE player_statistics (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        playerId  INTEGER NOT NULL UNIQUE,
        points    INTEGER NOT NULL DEFAULT 0,
        matches   INTEGER NOT NULL DEFAULT 0,
        updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `)

    await source.execute(`
      CREATE TABLE counters (
        name  TEXT    NOT NULL UNIQUE,
        value INTEGER NOT NULL DEFAULT 0
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM player_statistics')
    await source.execute('DELETE FROM counters')
  })

  // ─── Raw DataTable.upsert ──────────────────────────────────────────────────

  test('DataTable.upsert inserts when there is no conflict', async () => {
    const affected = await DB.table('counters').upsert([{ name: 'visits', value: 1 }], 'name')

    expect(affected).toBeGreaterThanOrEqual(1)

    const row = await DB.table('counters').where('name', 'visits').first()

    expect(row?.value).toBe(1)
  })

  test('DataTable.upsert updates the conflicting row', async () => {
    await DB.table('counters').upsert([{ name: 'visits', value: 1 }], 'name')
    await DB.table('counters').upsert([{ name: 'visits', value: 5 }], 'name')

    const rows = await DB.table('counters').where('name', 'visits').get()

    expect(rows).toHaveLength(1)
    expect(rows[0].value).toBe(5)
  })

  test('DataTable.upsert only updates the listed columns', async () => {
    await DB.table('player_statistics').upsert([{ playerId: 1, points: 10, matches: 2 }], 'playerId')
    // Conflict: only `points` should change, `matches` must be preserved.
    await DB.table('player_statistics').upsert([{ playerId: 1, points: 99, matches: 0 }], 'playerId', ['points'])

    const row = await DB.table('player_statistics').where('playerId', 1).first()

    expect(row?.points).toBe(99)
    expect(row?.matches).toBe(2)
  })

  test('DataTable.upsert inserts multiple rows at once', async () => {
    await DB.table('player_statistics').upsert(
      [
        { playerId: 1, points: 10, matches: 1 },
        { playerId: 2, points: 20, matches: 2 }
      ],
      'playerId'
    )

    const count = await DB.table('player_statistics').count()

    expect(count).toBe(2)
  })

  // ─── Entity-level upsert (Eloquent-style) ──────────────────────────────────

  test('Entity.upsert inserts a new row and applies casts', async () => {
    const date = new Date('2026-06-23T10:00:00.000Z')

    await PlayerStatistics.upsert([{ playerId: 7, points: 100, matches: 5, updatedAt: date }], 'playerId')

    const row = await PlayerStatistics.where('playerId', 7).first()

    expect(row).not.toBeNull()
    expect(row!.points).toBe(100)
    expect(row!.matches).toBe(5)
    expect(row!.updatedAt).toBeInstanceOf(Date)
    expect(row!.updatedAt.getTime()).toBe(date.getTime())
  })

  test('Entity.upsert updates an existing row by its unique column', async () => {
    const first = new Date('2026-06-23T10:00:00.000Z')
    const second = new Date('2026-06-24T10:00:00.000Z')

    await PlayerStatistics.upsert([{ playerId: 7, points: 100, matches: 5, updatedAt: first }], 'playerId')
    await PlayerStatistics.upsert([{ playerId: 7, points: 250, matches: 9, updatedAt: second }], 'playerId', [
      'points',
      'matches',
      'updatedAt'
    ])

    const rows = await PlayerStatistics.where('playerId', 7).get()

    expect(rows).toHaveLength(1)
    expect(rows[0].points).toBe(250)
    expect(rows[0].matches).toBe(9)
    expect(rows[0].updatedAt.getTime()).toBe(second.getTime())
  })

  test('Entity.upsert defaults to updating every non-unique column', async () => {
    await PlayerStatistics.upsert([{ playerId: 7, points: 1, matches: 1, updatedAt: new Date() }], 'playerId')
    await PlayerStatistics.upsert([{ playerId: 7, points: 2, matches: 3, updatedAt: new Date() }], 'playerId')

    const row = await PlayerStatistics.where('playerId', 7).first()

    expect(row!.points).toBe(2)
    expect(row!.matches).toBe(3)
  })
})
