import { BaseEntity, Column, DB, Entity, SqliteDataSource, SqliteQueryBuilder, UpsertQuery } from '../src'

// ─── Model ───────────────────────────────────────────────────────────────────

@Entity({ table: 'player_statistics' })
class PlayerStatistics extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  playerId!: number

  @Column({ cast: 'number' })
  points!: number

  @Column({ cast: 'number' })
  matches!: number

  @Column({ cast: 'date' })
  updatedAt!: Date
}

describe('Upsert — insert or update on conflict', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE player_statistics (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        playerId  INTEGER NOT NULL UNIQUE,
        points    INTEGER NOT NULL DEFAULT 0,
        matches   INTEGER NOT NULL DEFAULT 0,
        updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `)

    await source.execute(`
      CREATE TABLE counters (
        name  TEXT    NOT NULL UNIQUE,
        value INTEGER NOT NULL DEFAULT 0
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM player_statistics')
    await source.execute('DELETE FROM counters')
  })

  // ─── Raw DataTable.upsert ──────────────────────────────────────────────────

  test('DataTable.upsert inserts when there is no conflict', async () => {
    const affected = await DB.table('counters').upsert([{ name: 'visits', value: 1 }], 'name')

    expect(affected).toBeGreaterThanOrEqual(1)

    const row = await DB.table('counters').where('name', 'visits').first()

    expect(row?.value).toBe(1)
  })

  test('DataTable.upsert updates the conflicting row', async () => {
    await DB.table('counters').upsert([{ name: 'visits', value: 1 }], 'name')
    await DB.table('counters').upsert([{ name: 'visits', value: 5 }], 'name')

    const rows = await DB.table('counters').where('name', 'visits').get()

    expect(rows).toHaveLength(1)
    expect(rows[0].value).toBe(5)
  })

  test('DataTable.upsert only updates the listed columns', async () => {
    await DB.table('player_statistics').upsert([{ playerId: 1, points: 10, matches: 2 }], 'playerId')
    // Conflict: only `points` should change, `matches` must be preserved.
    await DB.table('player_statistics').upsert([{ playerId: 1, points: 99, matches: 0 }], 'playerId', ['points'])

    const row = await DB.table('player_statistics').where('playerId', 1).first()

    expect(row?.points).toBe(99)
    expect(row?.matches).toBe(2)
  })

  test('DataTable.upsert inserts multiple rows at once', async () => {
    await DB.table('player_statistics').upsert(
      [
        { playerId: 1, points: 10, matches: 1 },
        { playerId: 2, points: 20, matches: 2 }
      ],
      'playerId'
    )

    const count = await DB.table('player_statistics').count()

    expect(count).toBe(2)
  })

  // ─── Entity-level upsert (Eloquent-style) ──────────────────────────────────

  test('Entity.upsert inserts a new row and applies casts', async () => {
    const date = new Date('2026-06-23T10:00:00.000Z')

    await PlayerStatistics.upsert([{ playerId: 7, points: 100, matches: 5, updatedAt: date }], 'playerId')

    const row = await PlayerStatistics.where('playerId', 7).first()

    expect(row).not.toBeNull()
    expect(row!.points).toBe(100)
    expect(row!.matches).toBe(5)
    expect(row!.updatedAt).toBeInstanceOf(Date)
    expect(row!.updatedAt.getTime()).toBe(date.getTime())
  })

  test('Entity.upsert updates an existing row by its unique column', async () => {
    const first = new Date('2026-06-23T10:00:00.000Z')
    const second = new Date('2026-06-24T10:00:00.000Z')

    await PlayerStatistics.upsert([{ playerId: 7, points: 100, matches: 5, updatedAt: first }], 'playerId')
    await PlayerStatistics.upsert([{ playerId: 7, points: 250, matches: 9, updatedAt: second }], 'playerId', [
      'points',
      'matches',
      'updatedAt'
    ])

    const rows = await PlayerStatistics.where('playerId', 7).get()

    expect(rows).toHaveLength(1)
    expect(rows[0].points).toBe(250)
    expect(rows[0].matches).toBe(9)
    expect(rows[0].updatedAt.getTime()).toBe(second.getTime())
  })

  test('Entity.upsert defaults to updating every non-unique column', async () => {
    await PlayerStatistics.upsert([{ playerId: 7, points: 1, matches: 1, updatedAt: new Date() }], 'playerId')
    await PlayerStatistics.upsert([{ playerId: 7, points: 2, matches: 3, updatedAt: new Date() }], 'playerId')

    const row = await PlayerStatistics.where('playerId', 7).first()

    expect(row!.points).toBe(2)
    expect(row!.matches).toBe(3)
  })

  // ─── BATCH upsert (insert + update in a single statement) ──────────────────

  test('a batch UpsertQuery builds one multi-row INSERT ... ON CONFLICT statement', () => {
    const statement = new SqliteQueryBuilder().buildQuery(
      new UpsertQuery('player_statistics')
        .setRows([
          { playerId: 1, points: 10 },
          { playerId: 2, points: 20 },
          { playerId: 3, points: 30 }
        ])
        .setConflictColumns(['playerId'])
        .setUpdateColumns(['points'])
    )

    expect(statement.sql).toBe(
      'INSERT INTO player_statistics (playerId, points) VALUES (?, ?), (?, ?), (?, ?) ' +
        'ON CONFLICT (playerId) DO UPDATE SET points = EXCLUDED.points'
    )
    expect(statement.bindings).toEqual([1, 10, 2, 20, 3, 30])
  })

  test('DataTable.upsert inserts and updates within the same batch call', async () => {
    // Seed one existing row.
    await DB.table('player_statistics').upsert([{ playerId: 1, points: 10, matches: 1 }], 'playerId')

    // Single batch: playerId 1 conflicts (→ update), playerId 2 & 3 are new (→ insert).
    await DB.table('player_statistics').upsert(
      [
        { playerId: 1, points: 99, matches: 9 },
        { playerId: 2, points: 20, matches: 2 },
        { playerId: 3, points: 30, matches: 3 }
      ],
      'playerId',
      ['points', 'matches']
    )

    const rows = await DB.table('player_statistics').orderBy('playerId').get()

    expect(rows).toHaveLength(3)
    expect(rows.map((r) => Number(r.playerId))).toEqual([1, 2, 3])
    expect(rows.map((r) => Number(r.points))).toEqual([99, 20, 30])
    expect(rows.map((r) => Number(r.matches))).toEqual([9, 2, 3])
  })

  test('DataTable.upsert respects the update column list across the whole batch', async () => {
    await DB.table('player_statistics').upsert(
      [
        { playerId: 1, points: 10, matches: 5 },
        { playerId: 2, points: 20, matches: 6 }
      ],
      'playerId'
    )

    // Re-upsert the same keys updating only `points`; `matches` must be preserved.
    await DB.table('player_statistics').upsert(
      [
        { playerId: 1, points: 111, matches: 0 },
        { playerId: 2, points: 222, matches: 0 }
      ],
      'playerId',
      ['points']
    )

    const rows = await DB.table('player_statistics').orderBy('playerId').get()

    expect(rows.map((r) => Number(r.points))).toEqual([111, 222])
    expect(rows.map((r) => Number(r.matches))).toEqual([5, 6])
  })

  test('Entity.upsert handles a mixed insert/update batch and applies casts', async () => {
    const seeded = new Date('2026-06-23T10:00:00.000Z')
    const updated = new Date('2026-06-25T10:00:00.000Z')

    await PlayerStatistics.upsert([{ playerId: 7, points: 100, matches: 5, updatedAt: seeded }], 'playerId')

    await PlayerStatistics.upsert(
      [
        { playerId: 7, points: 250, matches: 9, updatedAt: updated }, // existing → update
        { playerId: 8, points: 40, matches: 2, updatedAt: updated }, // new → insert
        { playerId: 9, points: 60, matches: 4, updatedAt: updated } // new → insert
      ],
      'playerId',
      ['points', 'matches', 'updatedAt']
    )

    const rows = await PlayerStatistics.orderBy('playerId').get()

    expect(rows).toHaveLength(3)
    expect(rows.map((r) => r.playerId)).toEqual([7, 8, 9])
    expect(rows.map((r) => r.points)).toEqual([250, 40, 60])
    expect(rows[0].updatedAt).toBeInstanceOf(Date)
    expect(rows[0].updatedAt.getTime()).toBe(updated.getTime())
  })

  // ─── Upsert keyed on the auto-generated primary key ────────────────────────

  test('Entity.upsert keyed on the auto-generated primary key updates in place (no duplication)', async () => {
    const date = new Date('2026-06-23T10:00:00.000Z')

    await PlayerStatistics.upsert(
      [
        { playerId: 1, points: 10, matches: 1, updatedAt: date },
        { playerId: 2, points: 20, matches: 2, updatedAt: date }
      ],
      'playerId'
    )

    const seeded = await PlayerStatistics.orderBy('playerId').get()

    expect(seeded).toHaveLength(2)

    // Upsert keyed on the auto-generated `id`. The conflict target must be written
    // into the INSERT, otherwise ON CONFLICT (id) never matches and every row is
    // inserted as a duplicate instead of being updated.
    await PlayerStatistics.upsert(
      seeded.map((row) => ({
        id: row.id,
        playerId: row.playerId,
        points: row.points + 5,
        matches: row.matches,
        updatedAt: date
      })),
      'id',
      ['points']
    )

    const rows = await PlayerStatistics.orderBy('playerId').get()

    expect(rows).toHaveLength(2) // updated in place, not duplicated
    expect(rows.map((r) => Number(r.points))).toEqual([15, 25])
  })

  test('a batch UpsertQuery keyed on the primary key includes the id column', () => {
    const statement = new SqliteQueryBuilder().buildQuery(
      new UpsertQuery('player_statistics')
        .setRows([
          { id: 1, playerId: 1, points: 10 },
          { id: 2, playerId: 2, points: 20 }
        ])
        .setConflictColumns(['id'])
        .setUpdateColumns(['points'])
    )

    expect(statement.sql).toBe(
      'INSERT INTO player_statistics (id, playerId, points) VALUES (?, ?, ?), (?, ?, ?) ' +
        'ON CONFLICT (id) DO UPDATE SET points = EXCLUDED.points'
    )
    expect(statement.bindings).toEqual([1, 1, 10, 2, 2, 20])
  })
})
