import { CastType } from '../CastType'
import { registerEntityMeta } from '../EntityRepository'
import { Relationship } from '../Relationship'
import { registry } from './metadata'

export interface EntityOptions {
  /** Database table name. Defaults to lowercase class name + 's'. */
  table?: string
  /** Primary key column name. Defaults to 'id'. */
  primaryKey?: string
  /**
   * Registered DataSource name. When set, the entity operates on
   * DB.source(sourceName); otherwise it operates directly on DB.
   */
  source?: string | null
}

/**
 * Marks a class as a database entity.
 *
 * Reads the metadata accumulated by the property decorators (@Column, @HasMany, …)
 * and registers it in the EntityRepository's internal store via registerEntityMeta().
 *
 * The entity class itself is never modified — no static properties are added.
 */
export function Entity(options?: EntityOptions) {
  return function <T extends { new (...args: any[]): {} }>(EntityClass: T): T {
    // Read metadata accumulated by property decorators on the class prototype.
    const meta = registry.get(EntityClass.prototype) ?? {
      columns: [],
      relationships: [],
      serializableFields: [],
      nonSerializableFields: []
    }
    const tableName = options?.table ?? EntityClass.name.toLowerCase() + 's'
    const primaryKeyMeta = meta.columns.find((c) => c.primaryKey)
    const primaryKeyCol =
      (primaryKeyMeta && (primaryKeyMeta.columnName ?? primaryKeyMeta.name)) ?? options?.primaryKey ?? 'id'
    const fieldNames = meta.columns.map((c) => c.name)
    // Property name → database column name (defaults to the property name)
    const columnsMap: Record<string, string> = {}

    meta.columns.forEach((c) => {
      columnsMap[c.name] = c.columnName ?? c.name
    })

    const autoGeneratedFields = meta.columns.filter((c) => c.autoGenerated).map((c) => c.name)
    const castsMap: Record<string, CastType> = {}

    meta.columns.forEach((c) => {
      if (c.cast) {
        castsMap[c.name] = c.cast
      }
    })

    const relsMap: Record<string, Relationship> = {}

    meta.relationships.forEach((r) => {
      relsMap[r.name] = r.relationship
    })

    // Register metadata in the EntityRepository's internal store.
    // The class itself is returned untouched.
    registerEntityMeta(EntityClass, {
      table: tableName,
      primaryKey: primaryKeyCol,
      fields: fieldNames,
      columnsMap,
      autoGeneratedFields,
      casts: castsMap,
      relationships: relsMap,
      serializableFields: meta.serializableFields,
      nonSerializableFields: meta.nonSerializableFields,
      source: options?.source ?? null
    })

    return EntityClass
  }
}
