import { CastType } from '../CastType'
import { Relationship } from '../Relationship'

// ── Metadata registry ─────────────────────────────────────────────────────────
// Decorators run before the class decorator, storing per-prototype metadata.
// @Entity reads it all and injects everything onto the enhanced class.

export interface ColumnMeta {
  name: string
  columnName?: string
  cast?: CastType
  primaryKey?: boolean
  autoGenerated?: boolean
}

export interface RelationshipMeta {
  name: string
  relationship: Relationship
}

export interface PrototypeMeta {
  columns: ColumnMeta[]
  relationships: RelationshipMeta[]
  serializableFields: string[]
  nonSerializableFields: string[]
}

export const registry = new WeakMap<object, PrototypeMeta>()

export function getOrCreate(proto: object): PrototypeMeta {
  if (!registry.has(proto)) {
    registry.set(proto, { columns: [], relationships: [], serializableFields: [], nonSerializableFields: [] })
  }

  return registry.get(proto)!
}
