import { DataSet } from '../database/DataSet'
import { DataSource } from '../database/DataSource'
import { DB } from '../database/DB'
import { PaginationResult } from '../database/PaginationResult'
import { Field, InsertQuery, UpsertQuery } from '../database/query'
import { Condition, ConditionGroup, ExistsSubquery } from '../database/query/conditions'
import { OrderByDirection } from '../database/query/features/HasOrderByFields'
import { CastType } from './CastType'
import { applyCast, applyCastForStorage } from './decorators/casts'
import { EntityQuery } from './EntityQuery'
import { Relationship } from './Relationship'

// ── Serialization helpers ───────────────────────────────────────────────────────

/**
 * Strict ISO-8601 date-time matcher used to revive Date values from plain
 * objects when a column was not explicitly declared with `cast: 'date'`.
 * Requires the full "T" time component plus an explicit timezone (Z or ±hh:mm)
 * so ordinary strings are never misinterpreted as dates.
 */
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/

// ── Entity metadata ───────────────────────────────────────────────────────────

export interface EntityMeta {
  table: string
  primaryKey: string
  fields: string[]
  columnsMap: Record<string, string>
  autoGeneratedFields: string[]
  casts: Record<string, CastType>
  relationships: Record<string, Relationship>
  serializableFields: string[]
  nonSerializableFields: string[]
  source: string | null
}

/**
 * Internal store: entity constructor → metadata.
 * Populated exclusively by registerEntityMeta(), called from the @Entity decorator.
 * Decorators never write anything onto the entity class itself.
 */
const _metaStore = new Map<any, EntityMeta>()

/**
 * Called by the @Entity decorator to register an entity's metadata.
 * This is the only place that writes to _metaStore.
 */
export function registerEntityMeta(entityClass: any, meta: EntityMeta): void {
  _metaStore.set(entityClass, meta)
  // Invalidate any cached repository so it picks up fresh metadata
  _repoCache.delete(entityClass)
  // Invalidate booted state so booted() is called again with fresh metadata
  _bootedClasses.delete(entityClass)
}

// ── Global scopes ─────────────────────────────────────────────────────────────

/** entity class → (scope name → scope function) */
const _globalScopesStore = new Map<any, Map<string, (query: any) => void | Promise<void>>>()
/** Tracks which entity classes have already had booted() called. */
const _bootedClasses = new Set<any>()

/**
 * Registers a named global scope for an entity class.
 * Called from BaseEntity.addGlobalScope() or directly.
 */
export function addGlobalScopeToStore(entityClass: any, name: string, fn: (query: any) => void | Promise<void>): void {
  if (!_globalScopesStore.has(entityClass)) {
    _globalScopesStore.set(entityClass, new Map())
  }

  _globalScopesStore.get(entityClass)!.set(name, fn)
}

/**
 * Returns all registered global scopes for an entity class.
 */
export function getGlobalScopes(entityClass: any): Map<string, (query: any) => void | Promise<void>> {
  return _globalScopesStore.get(entityClass) ?? new Map()
}

/**
 * Calls entityClass.booted() once per class (idempotent).
 * Invoked by Repository.get() the first time a repo is created for a class.
 */
export function bootEntityClass(entityClass: any): void {
  if (_bootedClasses.has(entityClass)) {
    return
  }

  _bootedClasses.add(entityClass)

  if (typeof (entityClass as any).booted === 'function') {
    ;(entityClass as any).booted()
  }
}

// ── Dirty tracking ────────────────────────────────────────────────────────────

/**
 * instance → snapshot of property values as of the last hydration (fromRow /
 * fromJSON) or save(). Used to compute which fields actually changed so that
 * save() only UPDATEs the columns that are dirty. A WeakMap means snapshots
 * are garbage-collected automatically once the entity instance is no longer
 * referenced — no manual cleanup required.
 */
const _cleanSnapshots = new WeakMap<object, Record<string, any>>()
// ── Repository cache ──────────────────────────────────────────────────────────
const _repoCache = new Map<any, EntityRepository<any>>()

/**
 * Static facade for accessing entity repositories.
 *
 * Works with any entity class, whether or not it extends BaseEntity:
 *
 *   Repository.get(Country).where('name', 'Argentina').first()
 *   Repository.get(Country).save(countryInstance)
 *   Repository.get(Country).delete(countryInstance)
 */
export class Repository {
  static get<T>(entityClass: new (...args: any[]) => T): EntityRepository<T> {
    if (!_repoCache.has(entityClass)) {
      _repoCache.set(entityClass, new EntityRepository<T>(entityClass))
      bootEntityClass(entityClass)
    }

    return _repoCache.get(entityClass)! as EntityRepository<T>
  }
}

// ── EntityRepository ──────────────────────────────────────────────────────────

/**
 * All query, hydration, and persistence logic for a single entity class.
 * This is the single source of truth — BaseEntity methods are thin delegates
 * to this class, and plain (non-BaseEntity) entities use it directly via
 * Repository.get(EntityClass).
 *
 * Metadata is read from the module-level _metaStore, populated by @Entity.
 * The entity class itself is never modified by any decorator.
 */
export class EntityRepository<T> {
  private readonly _entityClass: new (...args: any[]) => T

  constructor(entityClass: new (...args: any[]) => T) {
    this._entityClass = entityClass
  }

  // ── Metadata accessors ─────────────────────────────────────────────────────

  private _meta(): EntityMeta {
    const meta = _metaStore.get(this._entityClass)

    if (!meta) {
      throw new Error(`Entity "${(this._entityClass as any).name}" has not been decorated with @Entity.`)
    }

    return meta
  }

  get table(): string {
    return this._meta().table
  }

  get primaryKey(): string {
    return this._meta().primaryKey
  }

  get fields(): string[] {
    return this._meta().fields
  }

  get columnsMap(): Record<string, string> {
    return this._meta().columnsMap
  }

  get autoGeneratedFields(): string[] {
    return this._meta().autoGeneratedFields
  }

  get casts(): Record<string, CastType> {
    return this._meta().casts
  }

  get relationships(): Record<string, Relationship> {
    return this._meta().relationships
  }

  get sourceName(): string | null {
    return this._meta().source
  }

  // ── DataSource ─────────────────────────────────────────────────────────────

  getSource(): DataSource {
    return this.sourceName ? DB.source(this.sourceName) : DB.getActiveSource()
  }

  // ── Query factory ──────────────────────────────────────────────────────────

  /** Creates a fresh EntityQuery for this entity. */
  query(): EntityQuery<T> {
    return new EntityQuery<T>(this, this.getSource().table(this.table))
  }

  // ── Hydration ──────────────────────────────────────────────────────────────

  /** Hydrates a database row into a typed entity instance, applying any casts. */
  fromRow(row: Record<string, any>): T {
    const instance = new (this._entityClass as any)()
    const fieldNames = this.fields
    const columnsMap = this.columnsMap
    const castsMap = this.casts
    const cols = fieldNames.length > 0 ? fieldNames : Object.keys(row)
    // Build a case-insensitive index to handle databases (e.g. PostgreSQL) that
    // return column names in lowercase regardless of how they were defined.
    const lowerRow: Record<string, any> = {}

    for (const key of Object.keys(row)) {
      lowerRow[key.toLowerCase()] = row[key]
    }

    for (const prop of cols) {
      const col = columnsMap[prop] ?? prop
      const hasExact = col in row
      const hasLower = col.toLowerCase() in lowerRow

      if (!hasExact && !hasLower) {
        continue
      }

      const rawValue = hasExact ? row[col] : lowerRow[col.toLowerCase()]
      const cast = castsMap[prop]

      instance[prop] = cast ? applyCast(rawValue, cast) : rawValue
    }

    this._markClean(instance)

    return instance
  }

  // ── Dirty tracking ──────────────────────────────────────────────────────────

  /** The set of property names tracked for dirty-checking on a given instance. */
  private _trackedFields(instance: T): string[] {
    const fieldNames = this.fields

    return fieldNames.length > 0
      ? fieldNames
      : Object.keys(instance as any).filter((k) => typeof (instance as any)[k] !== 'function')
  }

  /** Deep-clones a value so later in-place mutations don't corrupt the clean snapshot. */
  private _cloneValue(value: any): any {
    if (value instanceof Date) {
      return new Date(value.getTime())
    }

    if (Array.isArray(value)) {
      return value.map((item) => this._cloneValue(item))
    }

    if (value !== null && typeof value === 'object') {
      try {
        return JSON.parse(JSON.stringify(value))
      } catch {
        return value
      }
    }

    return value
  }

  /** Value-equality used for dirty checks: handles Date and plain object/array (json/array casts). */
  private _valuesEqual(a: any, b: any): boolean {
    if (a === b) {
      return true
    }

    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime()
    }

    if (a !== null && b !== null && typeof a === 'object' && typeof b === 'object') {
      return JSON.stringify(a) === JSON.stringify(b)
    }

    return false
  }

  /**
   * Snapshots the instance's current field values as "clean" — the baseline
   * against which future changes are compared. Called after hydration
   * (fromRow / fromJSON) and after every save().
   */
  private _markClean(instance: T): void {
    const snapshot: Record<string, any> = {}

    for (const prop of this._trackedFields(instance)) {
      const value = (instance as any)[prop]

      if (value !== undefined) {
        snapshot[prop] = this._cloneValue(value)
      }
    }

    _cleanSnapshots.set(instance as any, snapshot)
  }

  /**
   * Returns the property names whose current value differs from the last
   * clean snapshot (or every set property, if the instance was never
   * hydrated/saved — e.g. a brand-new `new User()`).
   */
  private _dirtyFields(instance: T): string[] {
    const snapshot = _cleanSnapshots.get(instance as any)
    const dirty: string[] = []

    for (const prop of this._trackedFields(instance)) {
      const value = (instance as any)[prop]

      if (value === undefined) {
        continue
      }

      if (snapshot && prop in snapshot && this._valuesEqual(snapshot[prop], value)) {
        continue
      }

      dirty.push(prop)
    }

    return dirty
  }

  /**
   * True if the instance (or, when given, a specific property) has unsaved
   * changes relative to its last hydration/save.
   *
   *   user.email = 'new@x.com'
   *   Repository.get(User).isDirty(user)          // true
   *   Repository.get(User).isDirty(user, 'name')   // false
   */
  isDirty(instance: T, field?: string): boolean {
    const dirty = this._dirtyFields(instance)

    return field ? dirty.includes(field) : dirty.length > 0
  }

  /**
   * Returns a `{ property: value }` map of only the properties that changed
   * since the instance's last hydration/save.
   */
  getDirty(instance: T): Record<string, any> {
    const result: Record<string, any> = {}

    for (const prop of this._dirtyFields(instance)) {
      result[prop] = (instance as any)[prop]
    }

    return result
  }

  // ── Serialization ────────────────────────────────────────────────────────────

  /**
   * Serializes an entity instance into a plain, JSON-safe object.
   *
   * - Own data properties and prototype getters are included.
   * - `Date` values are converted to ISO-8601 strings.
   * - Loaded relationships (and any nested entity values) are serialized
   *   recursively into plain objects.
   *
   * Works with any entity class, whether or not it extends BaseEntity:
   *
   *   Repository.get(Country).toJSON(countryInstance)
   */
  toJSON(instance: T): Record<string, any> {
    return this._serialize(instance, new WeakSet())
  }

  /**
   * Re-hydrates a plain object (typically the output of toJSON, or the result
   * of JSON.parse on a serialized entity) back into a typed entity instance.
   *
   * - Fields declared with a cast are coerced through it (e.g. `cast: 'date'`
   *   revives Date instances, `cast: 'json'` keeps the parsed object, …).
   * - String values that look like full ISO-8601 timestamps are revived into
   *   Date instances even when no cast was declared.
   * - Relationships are re-hydrated recursively into their related entity types
   *   (single instance for hasOne/belongsTo, array for hasMany/*Through).
   *
   * Works with any entity class, whether or not it extends BaseEntity:
   *
   *   Repository.get(Country).fromJSON(countryInstanceJSON)
   */
  fromJSON(json: Record<string, any>): T {
    const instance = new (this._entityClass as any)()

    if (json == null) {
      return instance
    }

    const relationships = this.relationships
    const castsMap = this.casts

    for (const key of Object.keys(json)) {
      const value = json[key]
      const rel = relationships[key]

      if (rel) {
        if (value == null) {
          this._assign(instance, key, value)
        } else {
          const relatedRepo = Repository.get(rel.related())

          this._assign(
            instance,
            key,
            Array.isArray(value) ? value.map((item) => relatedRepo.fromJSON(item)) : relatedRepo.fromJSON(value)
          )
        }

        continue
      }

      const cast = castsMap[key]

      this._assign(instance, key, cast ? applyCast(value, cast) : this._reviveValue(value))
    }

    this._markClean(instance)

    return instance
  }

  /** Builds the plain object for an instance, guarding against circular graphs. */
  private _serialize(instance: any, seen: WeakSet<object>): Record<string, any> {
    const result: Record<string, any> = {}

    if (instance == null) {
      return result
    }

    seen.add(instance)

    for (const key of this._serializableKeys(instance)) {
      let value: any

      try {
        value = instance[key]
      } catch {
        continue // skip getters that throw (e.g. unloaded relationships)
      }

      result[key] = this._serializeValue(value, seen)
    }

    return result
  }

  /** Recursively converts a single value into a JSON-safe representation. */
  private _serializeValue(value: any, seen: WeakSet<object>): any {
    if (value == null) {
      return value
    }

    if (value instanceof Date) {
      return value.toISOString()
    }

    if (Array.isArray(value)) {
      return value.map((item) => this._serializeValue(item, seen))
    }

    if (typeof value === 'object') {
      const ctor = value.constructor

      // Nested registered entity (a loaded relationship) → serialize recursively.
      if (ctor && _metaStore.has(ctor)) {
        if (seen.has(value)) {
          return undefined // break circular references
        }

        return Repository.get(ctor)._serialize(value, seen)
      }
    }

    return value
  }

  /** Collects own enumerable properties plus @Serializable() getters, minus @Serializable(false) fields. */
  private _serializableKeys(instance: any): string[] {
    const meta = this._meta()
    const keys = new Set<string>(Object.keys(instance))

    for (const key of meta.serializableFields) {
      keys.add(key)
    }

    for (const key of meta.nonSerializableFields) {
      keys.delete(key)
    }

    return [...keys]
  }

  /** Revives a non-cast value, turning full ISO-8601 strings into Date instances. */
  private _reviveValue(value: any): any {
    if (typeof value === 'string' && ISO_DATE_RE.test(value)) {
      return new Date(value)
    }

    return value
  }

  /** Assigns a value, silently skipping read-only / getter-only properties. */
  private _assign(instance: any, key: string, value: any): void {
    try {
      instance[key] = value
    } catch {
      // ignore computed getters / read-only properties
    }
  }

  // ── Terminal query methods ─────────────────────────────────────────────────

  async find(id: any): Promise<T | null> {
    return this.query().find(id)
  }

  async get(): Promise<T[]> {
    return this.query().get()
  }

  async first(): Promise<T | null> {
    return this.query().first()
  }

  async count(column: Field = '*'): Promise<number> {
    return this.query().count(column)
  }

  async paginate(perPage = 15, page = 1): Promise<PaginationResult<T>> {
    return this.query().paginate(perPage, page)
  }

  // ── Chainable query builder methods ───────────────────────────────────────

  where(callback: (group: ConditionGroup) => void): EntityQuery<T>
  where(condition: Condition): EntityQuery<T>
  where(field: Field, value: any): EntityQuery<T>
  where(field: Field, operator: string, value: any): EntityQuery<T>
  where(...args: any[]): EntityQuery<T> {
    return (this.query() as any).where(...args)
  }

  whereIn(field: Field, values: any[]): EntityQuery<T> {
    return this.query().whereIn(field, values)
  }

  whereNotIn(field: Field, values: any[]): EntityQuery<T> {
    return this.query().whereNotIn(field, values)
  }

  whereBetween(field: Field, range: [any, any]): EntityQuery<T> {
    return this.query().whereBetween(field, range)
  }

  whereNotBetween(field: Field, range: [any, any]): EntityQuery<T> {
    return this.query().whereNotBetween(field, range)
  }

  whereNull(field: Field): EntityQuery<T> {
    return this.query().whereNull(field)
  }

  whereNotNull(field: Field): EntityQuery<T> {
    return this.query().whereNotNull(field)
  }

  whereLike(field: Field, pattern: string, caseSensitive = false): EntityQuery<T> {
    return this.query().whereLike(field, pattern, caseSensitive)
  }

  whereNotLike(field: Field, pattern: string, caseSensitive = false): EntityQuery<T> {
    return this.query().whereNotLike(field, pattern, caseSensitive)
  }

  whereColumn(field: Field, column: Field): EntityQuery<T>
  whereColumn(field: Field, operator: string, column: Field): EntityQuery<T>
  whereColumn(...args: any[]): EntityQuery<T> {
    return (this.query() as any).whereColumn(...args)
  }

  whereExists(subquery: ExistsSubquery): EntityQuery<T> {
    return this.query().whereExists(subquery)
  }

  whereNotExists(subquery: ExistsSubquery): EntityQuery<T> {
    return this.query().whereNotExists(subquery)
  }

  orderBy(field: Field, direction?: OrderByDirection): EntityQuery<T> {
    return this.query().orderBy(field, direction)
  }

  orderByDesc(field: Field): EntityQuery<T> {
    return this.query().orderByDesc(field)
  }

  groupBy(...fields: Field[]): EntityQuery<T> {
    return this.query().groupBy(...fields)
  }

  limit(value: number): EntityQuery<T> {
    return this.query().limit(value)
  }

  offset(value: number): EntityQuery<T> {
    return this.query().offset(value)
  }

  select(...fields: (Field | Field[])[]): EntityQuery<T> {
    return this.query().select(...fields)
  }

  with(relations: Record<string, (query: EntityQuery<T>) => void>): EntityQuery<T>
  with(relations: string | string[], ...rest: string[]): EntityQuery<T>
  with(relations: any, ...rest: string[]): EntityQuery<T> {
    return (this.query() as any).with(relations, ...rest)
  }

  when(condition: any, callback: (query: EntityQuery<T>) => void): EntityQuery<T> {
    return this.query().when(condition, callback)
  }

  whereHas(relationName: string, callback?: (query: EntityQuery<T>) => void): EntityQuery<T> {
    return this.query().whereHas(relationName, callback)
  }

  orWhereHas(relationName: string, callback?: (query: EntityQuery<T>) => void): EntityQuery<T> {
    return this.query().orWhereHas(relationName, callback)
  }

  joinRelationship(relationName: string): EntityQuery<T> {
    return this.query().joinRelationship(relationName)
  }

  innerJoinRelationship(relationName: string): EntityQuery<T> {
    return this.query().innerJoinRelationship(relationName)
  }

  leftJoinRelationship(relationName: string): EntityQuery<T> {
    return this.query().leftJoinRelationship(relationName)
  }

  // ── Persistence ────────────────────────────────────────────────────────────

  /**
   * Persists an entity instance to the database.
   * - Primary key set   → UPDATE. Only properties that changed since the last
   *                       hydration/save (the "dirty" fields) are written —
   *                       untouched columns are left out of the SET clause
   *                       entirely. If nothing is dirty, no query is issued.
   * - Primary key unset → INSERT (auto-generated columns excluded; generated
   *                       PK is written back onto the instance).
   *
   * After a successful save, every written field is marked clean again, so a
   * subsequent save() only touches whatever changes next:
   *
   *   user.email = 'new@x.com'
   *   await user.save()   // UPDATE users SET email = 'new@x.com' WHERE id = ?
   *   await user.save()   // nothing dirty — no query issued
   */
  async save(instance: T): Promise<void> {
    const pk = this.primaryKey
    const autoGeneratedFields = this.autoGeneratedFields
    const castsMap = this.casts
    const columnsMap = this.columnsMap
    const pkProp = Object.keys(columnsMap).find((p) => columnsMap[p] === pk) ?? pk
    const source = this.getSource()
    const isUpdate = (instance as any)[pkProp] != null
    // On UPDATE only the properties that changed since the last hydration/save
    // are written. On INSERT there is no prior snapshot, so every set property
    // is written — matching the previous (always-write-everything) behaviour.
    const propsToWrite = isUpdate ? this._dirtyFields(instance) : this._trackedFields(instance)
    // Build the column→value row, skipping auto-generated columns
    const row: DataSet = {}

    for (const col of propsToWrite) {
      if (autoGeneratedFields.includes(col)) {
        continue
      }

      const value = (instance as any)[col]

      if (value === undefined) {
        continue
      }

      const cast = castsMap[col]

      row[columnsMap[col] ?? col] = cast ? applyCastForStorage(value, cast) : value
    }

    if (isUpdate) {
      // UPDATE — exclude PK from SET clause
      const updateRow = { ...row }

      delete updateRow[pk]

      if (Object.keys(updateRow).length > 0) {
        await source
          .table(this.table)
          .where(pk, (instance as any)[pkProp])
          .update(updateRow)
      }
    } else {
      // INSERT — read back the generated ID. When a transaction is in progress
      // for this source, reuse its connection (so the INSERT and the lastInsertId
      // read are part of the transaction) and leave its lifecycle to the
      // transaction; otherwise open and close a one-off connection.
      const active = source.getActiveConnection()
      const conn = active ?? (await source.getConnection())

      try {
        await conn.execute(new InsertQuery().setTable(this.table).setFields(row))

        if (autoGeneratedFields.includes(pkProp)) {
          ;(instance as any)[pkProp] = await conn.lastInsertId()
        }
      } finally {
        if (!active) {
          await conn.close()
        }
      }
    }

    // Every field is now in sync with the database — reset the dirty baseline.
    this._markClean(instance)
  }

  /**
   * Maps an entity-property record into a column-keyed storage row: auto-generated
   * columns and `undefined` values are skipped, property names are translated to
   * column names, and declared casts (`date`, `json`, `array`, …) are applied for
   * storage. Shared by insert() and upsert().
   *
   * `keepProps` forces the given properties to be written even when they are
   * auto-generated. upsert() uses it for the conflict-target columns: an
   * `ON CONFLICT (id) DO UPDATE` can only match when the auto-generated key `id`
   * is actually present in the INSERT, otherwise every row is inserted as new.
   */
  private _toStorageRow(value: Record<string, any>, keepProps: string[] = []): DataSet {
    const columnsMap = this.columnsMap
    const castsMap = this.casts
    const autoGeneratedFields = this.autoGeneratedFields
    const row: DataSet = {}

    for (const prop of Object.keys(value)) {
      if (autoGeneratedFields.includes(prop) && !keepProps.includes(prop)) {
        continue
      }

      const rawValue = value[prop]

      if (rawValue === undefined) {
        continue
      }

      const cast = castsMap[prop]

      row[columnsMap[prop] ?? prop] = cast ? applyCastForStorage(rawValue, cast) : rawValue
    }

    return row
  }

  /**
   * Inserts the given records in a single batch statement. Mirrors Eloquent's
   * `Model::insert($values)`:
   *
   *   await Repository.get(Match).insert([
   *     { roundId: 4, position: 0, homeCompetitorIds: [1], status: 0 },
   *     { roundId: 4, position: 1, homeCompetitorIds: [2], status: 0 }
   *   ])
   *
   * `values` are expressed in terms of entity property names; this method maps
   * them to column names and applies the declared casts for storage. Auto-generated
   * columns (e.g. the primary key) are never written and generated keys are not
   * read back onto the records (use save() for a single record when you need the
   * generated id). Returns the number of affected rows.
   */
  async insert(values: Record<string, any>[]): Promise<number> {
    if (values.length === 0) {
      return 0
    }

    const rows = values.map((value) => this._toStorageRow(value))
    const query = new InsertQuery(this.table).setRows(rows)

    return await this.getSource().execute(query)
  }

  /**
   * Inserts the given records, updating the conflicting columns when a row
   * already exists. Mirrors Eloquent's `Model::upsert($values, $uniqueBy, $update)`.
   *
   *   await Repository.get(PlayerStatistics).upsert(
   *     [{ playerId: 7, points: 120, updatedAt: new Date() }],
   *     'playerId',
   *     ['points', 'updatedAt']
   *   )
   *
   * `values`, `uniqueBy` and `update` are expressed in terms of entity property
   * names; this method maps them to column names and applies the declared casts
   * (e.g. `date`, `json`, `array`) for storage. When `update` is omitted, every
   * provided column that is not part of `uniqueBy` is updated. Auto-generated
   * columns are not written EXCEPT when they are part of `uniqueBy` (the conflict
   * target must be present in the INSERT for `ON CONFLICT` to match — e.g. an
   * upsert keyed on the auto-generated primary key).
   */
  async upsert(values: Record<string, any>[], uniqueBy: string | string[], update?: string[]): Promise<number> {
    if (values.length === 0) {
      return 0
    }

    const columnsMap = this.columnsMap
    const toColumn = (prop: string): string => columnsMap[prop] ?? prop
    const uniqueProps = Array.isArray(uniqueBy) ? uniqueBy : [uniqueBy]
    // Keep the conflict-target columns even if auto-generated, so ON CONFLICT can match.
    const rows: DataSet[] = values.map((value) => this._toStorageRow(value, uniqueProps))
    const query = new UpsertQuery(this.table)
      .setRows(rows)
      .setConflictColumns(uniqueProps.map(toColumn))
      .setUpdateColumns(update ? update.map(toColumn) : undefined)

    return await this.getSource().execute(query)
  }

  /**
   * Deletes an entity instance from the database by its primary key.
   * Throws if the primary key is not set on the instance.
   */
  async delete(instance: T): Promise<void> {
    const pk = this.primaryKey
    const columnsMap = this.columnsMap
    const pkProp = Object.keys(columnsMap).find((p) => columnsMap[p] === pk) ?? pk
    const pkValue = (instance as any)[pkProp]

    if (pkValue == null) {
      throw new Error('Cannot delete an entity without a primary key value.')
    }

    await this.getSource().table(this.table).where(pk, pkValue).delete()
  }
}
